package namesies;

import main.Global;
import util.PokeString;

public enum AbilityNamesies {
    // EVERYTHING BELOW IS GENERATED ###
	NO_ABILITY("No Ability"),
	OVERGROW("Overgrow"),
	CHLOROPHYLL("Chlorophyll"),
	BLAZE("Blaze"),
	SOLAR_POWER("Solar Power"),
	TORRENT("Torrent"),
	RAIN_DISH("Rain Dish"),
	SHIELD_DUST("Shield Dust"),
	SHED_SKIN("Shed Skin"),
	COMPOUNDEYES("Compoundeyes"),
	TINTED_LENS("Tinted Lens"),
	SWARM("Swarm"),
	SNIPER("Sniper"),
	KEEN_EYE("Keen Eye"),
	TANGLED_FEET("Tangled Feet"),
	GUTS("Guts"),
	INTIMIDATE("Intimidate"),
	STATIC("Static"),
	LIGHTNINGROD("Lightningrod"),
	SAND_VEIL("Sand Veil"),
	SAND_RUSH("Sand Rush"),
	POISON_POINT("Poison Point"),
	RIVALRY("Rivalry"),
	CUTE_CHARM("Cute Charm"),
	MAGIC_GUARD("Magic Guard"),
	FLASH_FIRE("Flash Fire"),
	DROUGHT("Drought"),
	FRISK("Frisk"),
	INNER_FOCUS("Inner Focus"),
	INFILTRATOR("Infiltrator"),
	STENCH("Stench"),
	EFFECT_SPORE("Effect Spore"),
	DRY_SKIN("Dry Skin"),
	ARENA_TRAP("Arena Trap"),
	TECHNICIAN("Technician"),
	LIMBER("Limber"),
	DAMP("Damp"),
	CLOUD_NINE("Cloud Nine"),
	VITAL_SPIRIT("Vital Spirit"),
	INSOMNIA("Insomnia"),
	ANGER_POINT("Anger Point"),
	SYNCHRONIZE("Synchronize"),
	NO_GUARD("No Guard"),
	OWN_TEMPO("Own Tempo"),
	CLEAR_BODY("Clear Body"),
	LIQUID_OOZE("Liquid Ooze"),
	ROCK_HEAD("Rock Head"),
	STURDY("Sturdy"),
	OBLIVIOUS("Oblivious"),
	MAGNET_PULL("Magnet Pull"),
	UNAWARE("Unaware"),
	SIMPLE("Simple"),
	EARLY_BIRD("Early Bird"),
	THICK_FAT("Thick Fat"),
	HYDRATION("Hydration"),
	SHELL_ARMOR("Shell Armor"),
	BATTLE_ARMOR("Battle Armor"),
	SKILL_LINK("Skill Link"),
	LEVITATE("Levitate"),
	FOREWARN("Forewarn"),
	HYPER_CUTTER("Hyper Cutter"),
	SOUNDPROOF("Soundproof"),
	RECKLESS("Reckless"),
	IRON_FIST("Iron Fist"),
	NATURAL_CURE("Natural Cure"),
	SERENE_GRACE("Serene Grace"),
	LEAF_GUARD("Leaf Guard"),
	SCRAPPY("Scrappy"),
	SWIFT_SWIM("Swift Swim"),
	WATER_VEIL("Water Veil"),
	FILTER("Filter"),
	FLAME_BODY("Flame Body"),
	RATTLED("Rattled"),
	MOXIE("Moxie"),
	IMPOSTER("Imposter"),
	ADAPTABILITY("Adaptability"),
	WATER_ABSORB("Water Absorb"),
	VOLT_ABSORB("Volt Absorb"),
	QUICK_FEET("Quick Feet"),
	TRACE("Trace"),
	DOWNLOAD("Download"),
	PRESSURE("Pressure"),
	IMMUNITY("Immunity"),
	SNOW_CLOAK("Snow Cloak"),
	MARVEL_SCALE("Marvel Scale"),
	MULTISCALE("Multiscale"),
	SHEER_FORCE("Sheer Force"),
	HUSTLE("Hustle"),
	HUGE_POWER("Huge Power"),
	SPEED_BOOST("Speed Boost"),
	MAGIC_BOUNCE("Magic Bounce"),
	SUPER_LUCK("Super Luck"),
	SHADOW_TAG("Shadow Tag"),
	OVERCOAT("Overcoat"),
	MAGMA_ARMOR("Magma Armor"),
	SUCTION_CUPS("Suction Cups"),
	STEADFAST("Steadfast"),
	SAND_STREAM("Sand Stream"),
	REGENERATOR("Regenerator"),
	POISON_HEAL("Poison Heal"),
	TRUANT("Truant"),
	WONDER_GUARD("Wonder Guard"),
	NORMALIZE("Normalize"),
	STALL("Stall"),
	PURE_POWER("Pure Power"),
	ROUGH_SKIN("Rough Skin"),
	SOLID_ROCK("Solid Rock"),
	WHITE_SMOKE("White Smoke"),
	TOXIC_BOOST("Toxic Boost"),
	ANTICIPATION("Anticipation"),
	STORM_DRAIN("Storm Drain"),
	COLOR_CHANGE("Color Change"),
	ICE_BODY("Ice Body"),
	LIGHT_METAL("Light Metal"),
	DRIZZLE("Drizzle"),
	AIR_LOCK("Air Lock"),
	DEFIANT("Defiant"),
	COMPETITIVE("Competitive"),
	FLOWER_GIFT("Flower Gift"),
	AFTERMATH("Aftermath"),
	HEATPROOF("Heatproof"),
	SAND_FORCE("Sand Force"),
	SNOW_WARNING("Snow Warning"),
	MOTOR_DRIVE("Motor Drive"),
	JUSTIFIED("Justified"),
	CURSED_BODY("Cursed Body"),
	SLOW_START("Slow Start"),
	BAD_DREAMS("Bad Dreams"),
	VICTORY_STAR("Victory Star"),
	CONTRARY("Contrary"),
	BIG_PECKS("Big Pecks"),
	POISON_TOUCH("Poison Touch"),
	PRANKSTER("Prankster"),
	WONDER_SKIN("Wonder Skin"),
	MUMMY("Mummy"),
	DEFEATIST("Defeatist"),
	WEAK_ARMOR("Weak Armor"),
	ILLUSION("Illusion"),
	ANALYTIC("Analytic"),
	SAP_SIPPER("Sap Sipper"),
	IRON_BARBS("Iron Barbs"),
	MOLD_BREAKER("Mold Breaker"),
	TERAVOLT("Teravolt"),
	TURBOBLAZE("Turboblaze"),
	RUN_AWAY("Run Away"),
	STICKY_HOLD("Sticky Hold"),
	KLUTZ("Klutz"),
	UNBURDEN("Unburden"),
	PICKPOCKET("Pickpocket"),
	HARVEST("Harvest"),
	PICKUP("Pickup"),
	UNNERVE("Unnerve"),
	HONEY_GATHER("Honey Gather"),
	GLUTTONY("Gluttony"),
	MULTITYPE("Multitype"),
	FORECAST("Forecast"),
	BULLETPROOF("Bulletproof"),
	AURA_BREAK("Aura Break"),
	FAIRY_AURA("Fairy Aura"),
	DARK_AURA("Dark Aura"),
	MAGICIAN("Magician"),
	CHEEK_POUCH("Cheek Pouch"),
	STRONG_JAW("Strong Jaw"),
	MEGA_LAUNCHER("Mega Launcher"),
	TOUGH_CLAWS("Tough Claws"),
	SWEET_VEIL("Sweet Veil"),
	AROMA_VEIL("Aroma Veil"),
	HEALER("Healer"),
	PIXILATE("Pixilate"),
	REFRIGERATE("Refrigerate"),
	STANCE_CHANGE("Stance Change"),
	FUR_COAT("Fur Coat"),
	GRASS_PELT("Grass Pelt"),
	FLOWER_VEIL("Flower Veil"),
	GALE_WINGS("Gale Wings"),
	PROTEAN("Protean");

    // EVERYTHING ABOVE IS GENERATED ###

    private String name;

    AbilityNamesies(String name) {
        this.name = name;
    }

	public String getName() {
		return this.name;
	}

	public static AbilityNamesies getValueOf(String name) {
		try {
			return AbilityNamesies.valueOf(PokeString.getNamesiesString(name));
		} catch (IllegalArgumentException exception) {
			Global.error(name + " does not have a valid AbilityNamesies value");
			return null;
		}
	}
}

