package namesies;

import main.Global;
import util.PokeString;
import util.StringUtils;

public enum AttackNamesies {
    // EVERYTHING BELOW IS GENERATED ###
	TACKLE("Tackle"),
	LEECH_SEED("Leech Seed"),
	THUNDER_WAVE("Thunder Wave"),
	POISON_POWDER("Poison Powder"),
	SLEEP_POWDER("Sleep Powder"),
	TOXIC("Toxic"),
	EMBER("Ember"),
	GROWL("Growl"),
	SCRATCH("Scratch"),
	VINE_WHIP("Vine Whip"),
	SONIC_BOOM("Sonic Boom"),
	SMOKESCREEN("Smokescreen"),
	TAKE_DOWN("Take Down"),
	STRUGGLE("Struggle"),
	RAZOR_LEAF("Razor Leaf"),
	SWEET_SCENT("Sweet Scent"),
	GROWTH("Growth"),
	DOUBLE_EDGE("Double-Edge"),
	SEED_BOMB("Seed Bomb"),
	SYNTHESIS("Synthesis"),
	RECOVER("Recover"),
	DRAGON_RAGE("Dragon Rage"),
	SCARY_FACE("Scary Face"),
	FIRE_FANG("Fire Fang"),
	FLAME_BURST("Flame Burst"),
	BITE("Bite"),
	SLASH("Slash"),
	TAIL_WHIP("Tail Whip"),
	SOLAR_BEAM("Solar Beam"),
	FLAMETHROWER("Flamethrower"),
	FLY("Fly"),
	FIRE_SPIN("Fire Spin"),
	INFERNO("Inferno"),
	DRAGON_CLAW("Dragon Claw"),
	SHADOW_CLAW("Shadow Claw"),
	AIR_SLASH("Air Slash"),
	WING_ATTACK("Wing Attack"),
	HEAT_WAVE("Heat Wave"),
	FLARE_BLITZ("Flare Blitz"),
	FLASH_CANNON("Flash Cannon"),
	BUBBLE("Bubble"),
	WITHDRAW("Withdraw"),
	WATER_GUN("Water Gun"),
	RAPID_SPIN("Rapid Spin"),
	REFLECT("Reflect"),
	SPIKY_SHIELD("Spiky Shield"),
	KINGS_SHIELD("King's Shield"),
	PROTECT("Protect"),
	DETECT("Detect"),
	QUICK_GUARD("Quick Guard"),
	ENDURE("Endure"),
	WATER_PULSE("Water Pulse"),
	CONFUSION_DAMAGE("ConfusionDamage"),
	CONFUSE_RAY("Confuse Ray"),
	AQUA_TAIL("Aqua Tail"),
	SKULL_BASH("Skull Bash"),
	IRON_DEFENSE("Iron Defense"),
	HYDRO_PUMP("Hydro Pump"),
	RAIN_DANCE("Rain Dance"),
	SUNNY_DAY("Sunny Day"),
	SANDSTORM("Sandstorm"),
	HAIL("Hail"),
	PETAL_DANCE("Petal Dance"),
	THRASH("Thrash"),
	HYPER_BEAM("Hyper Beam"),
	STRING_SHOT("String Shot"),
	BUG_BITE("Bug Bite"),
	HARDEN("Harden"),
	CONFUSION("Confusion"),
	STUN_SPORE("Stun Spore"),
	GUST("Gust"),
	SUPERSONIC("Supersonic"),
	PSYBEAM("Psybeam"),
	SILVER_WIND("Silver Wind"),
	TAILWIND("Tailwind"),
	MORNING_SUN("Morning Sun"),
	SAFEGUARD("Safeguard"),
	CAPTIVATE("Captivate"),
	BUG_BUZZ("Bug Buzz"),
	QUIVER_DANCE("Quiver Dance"),
	ENCORE("Encore"),
	POISON_STING("Poison Sting"),
	FURY_ATTACK("Fury Attack"),
	FALSE_SWIPE("False Swipe"),
	DISABLE("Disable"),
	FOCUS_ENERGY("Focus Energy"),
	TWINEEDLE("Twineedle"),
	RAGE("Rage"),
	PURSUIT("Pursuit"),
	TOXIC_SPIKES("Toxic Spikes"),
	PIN_MISSILE("Pin Missile"),
	AGILITY("Agility"),
	ASSURANCE("Assurance"),
	POISON_JAB("Poison Jab"),
	ENDEAVOR("Endeavor"),
	SAND_ATTACK("Sand Attack"),
	QUICK_ATTACK("Quick Attack"),
	TWISTER("Twister"),
	FEATHER_DANCE("Feather Dance"),
	ROOST("Roost"),
	THUNDER_SHOCK("Thunder Shock"),
	MIRROR_MOVE("Mirror Move"),
	HURRICANE("Hurricane"),
	HYPER_FANG("Hyper Fang"),
	SUCKER_PUNCH("Sucker Punch"),
	CRUNCH("Crunch"),
	SUPER_FANG("Super Fang"),
	SWORDS_DANCE("Swords Dance"),
	PECK("Peck"),
	LEER("Leer"),
	AERIAL_ACE("Aerial Ace"),
	DRILL_PECK("Drill Peck"),
	PLUCK("Pluck"),
	DRILL_RUN("Drill Run"),
	WRAP("Wrap"),
	GLARE("Glare"),
	SCREECH("Screech"),
	ACID("Acid"),
	STOCKPILE("Stockpile"),
	SPIT_UP("Spit Up"),
	SWALLOW("Swallow"),
	ACID_SPRAY("Acid Spray"),
	MUD_BOMB("Mud Bomb"),
	HAZE("Haze"),
	COIL("Coil"),
	GUNK_SHOT("Gunk Shot"),
	ICE_FANG("Ice Fang"),
	THUNDER_FANG("Thunder Fang"),
	ELECTRO_BALL("Electro Ball"),
	DOUBLE_TEAM("Double Team"),
	SLAM("Slam"),
	THUNDERBOLT("Thunderbolt"),
	FEINT("Feint"),
	DISCHARGE("Discharge"),
	LIGHT_SCREEN("Light Screen"),
	THUNDER("Thunder"),
	DEFENSE_CURL("Defense Curl"),
	SWIFT("Swift"),
	FURY_SWIPES("Fury Swipes"),
	ROLLOUT("Rollout"),
	FURY_CUTTER("Fury Cutter"),
	SAND_TOMB("Sand Tomb"),
	GYRO_BALL("Gyro Ball"),
	CRUSH_CLAW("Crush Claw"),
	DOUBLE_KICK("Double Kick"),
	POISON_TAIL("Poison Tail"),
	FLATTER("Flatter"),
	POISON_FANG("Poison Fang"),
	CHIP_AWAY("Chip Away"),
	BODY_SLAM("Body Slam"),
	EARTH_POWER("Earth Power"),
	SUPERPOWER("Superpower"),
	HORN_ATTACK("Horn Attack"),
	HORN_DRILL("Horn Drill"),
	MEGAHORN("Megahorn"),
	POUND("Pound"),
	SING("Sing"),
	DOUBLE_SLAP("Double Slap"),
	WISH("Wish"),
	MINIMIZE("Minimize"),
	WAKE_UP_SLAP("Wake-Up Slap"),
	COSMIC_POWER("Cosmic Power"),
	LUCKY_CHANT("Lucky Chant"),
	METRONOME("Metronome"),
	GRAVITY("Gravity"),
	MOONLIGHT("Moonlight"),
	STORED_POWER("Stored Power"),
	MIMIC("Mimic"),
	METEOR_MASH("Meteor Mash"),
	IMPRISON("Imprison"),
	WILL_O_WISP("Will-O-Wisp"),
	PAYBACK("Payback"),
	EXTRASENSORY("Extrasensory"),
	FIRE_BLAST("Fire Blast"),
	NASTY_PLOT("Nasty Plot"),
	ROUND("Round"),
	REST("Rest"),
	HYPER_VOICE("Hyper Voice"),
	LEECH_LIFE("Leech Life"),
	ASTONISH("Astonish"),
	AIR_CUTTER("Air Cutter"),
	MEAN_LOOK("Mean Look"),
	ACROBATICS("Acrobatics"),
	ABSORB("Absorb"),
	MEGA_DRAIN("Mega Drain"),
	NATURAL_GIFT("Natural Gift"),
	GIGA_DRAIN("Giga Drain"),
	AROMATHERAPY("Aromatherapy"),
	SPORE("Spore"),
	CROSS_POISON("Cross Poison"),
	X_SCISSOR("X-Scissor"),
	FORESIGHT("Foresight"),
	ODOR_SLEUTH("Odor Sleuth"),
	MIRACLE_EYE("Miracle Eye"),
	HOWL("Howl"),
	SIGNAL_BEAM("Signal Beam"),
	ZEN_HEADBUTT("Zen Headbutt"),
	PSYCHIC("Psychic"),
	MUD_SLAP("Mud-Slap"),
	MAGNITUDE("Magnitude"),
	BULLDOZE("Bulldoze"),
	DIG("Dig"),
	EARTHQUAKE("Earthquake"),
	FISSURE("Fissure"),
	NIGHT_SLASH("Night Slash"),
	TRI_ATTACK("Tri Attack"),
	FAKE_OUT("Fake Out"),
	FEINT_ATTACK("Feint Attack"),
	TAUNT("Taunt"),
	PAY_DAY("Pay Day"),
	POWER_GEM("Power Gem"),
	WATER_SPORT("Water Sport"),
	SOAK("Soak"),
	TRICK_OR_TREAT("Trick-or-Treat"),
	FORESTS_CURSE("Forest's Curse"),
	PSYCH_UP("Psych Up"),
	AMNESIA("Amnesia"),
	WONDER_ROOM("Wonder Room"),
	AQUA_JET("Aqua Jet"),
	COVET("Covet"),
	LOW_KICK("Low Kick"),
	KARATE_CHOP("Karate Chop"),
	SEISMIC_TOSS("Seismic Toss"),
	SWAGGER("Swagger"),
	CROSS_CHOP("Cross Chop"),
	PUNISHMENT("Punishment"),
	CLOSE_COMBAT("Close Combat"),
	DRAGON_ASCENT("Dragon Ascent"),
	FLAME_WHEEL("Flame Wheel"),
	REVERSAL("Reversal"),
	EXTREME_SPEED("Extreme Speed"),
	HYPNOSIS("Hypnosis"),
	BUBBLE_BEAM("Bubble Beam"),
	MUD_SHOT("Mud Shot"),
	BELLY_DRUM("Belly Drum"),
	SUBMISSION("Submission"),
	DYNAMIC_PUNCH("Dynamic Punch"),
	MIND_READER("Mind Reader"),
	LOCK_ON("Lock-On"),
	KINESIS("Kinesis"),
	BARRIER("Barrier"),
	TELEKINESIS("Telekinesis"),
	INGRAIN("Ingrain"),
	PSYCHO_CUT("Psycho Cut"),
	FUTURE_SIGHT("Future Sight"),
	DOOM_DESIRE("Doom Desire"),
	CALM_MIND("Calm Mind"),
	LOW_SWEEP("Low Sweep"),
	REVENGE("Revenge"),
	VITAL_THROW("Vital Throw"),
	WRING_OUT("Wring Out"),
	LEAF_TORNADO("Leaf Tornado"),
	LEAF_STORM("Leaf Storm"),
	LEAF_BLADE("Leaf Blade"),
	CONSTRICT("Constrict"),
	HEX("Hex"),
	SLUDGE_WAVE("Sludge Wave"),
	MUD_SPORT("Mud Sport"),
	ROCK_POLISH("Rock Polish"),
	ROCK_THROW("Rock Throw"),
	ROCK_BLAST("Rock Blast"),
	SMACK_DOWN("Smack Down"),
	STEALTH_ROCK("Stealth Rock"),
	STONE_EDGE("Stone Edge"),
	STEAMROLLER("Steamroller"),
	HEAVY_SLAM("Heavy Slam"),
	STOMP("Stomp"),
	FLAME_CHARGE("Flame Charge"),
	BOUNCE("Bounce"),
	CURSE("Curse"),
	YAWN("Yawn"),
	HEADBUTT("Headbutt"),
	SLACK_OFF("Slack Off"),
	HEAL_PULSE("Heal Pulse"),
	METAL_SOUND("Metal Sound"),
	SPARK("Spark"),
	MAGNET_BOMB("Magnet Bomb"),
	MIRROR_SHOT("Mirror Shot"),
	MAGNET_RISE("Magnet Rise"),
	ZAP_CANNON("Zap Cannon"),
	BRAVE_BIRD("Brave Bird"),
	UPROAR("Uproar"),
	ACUPRESSURE("Acupressure"),
	DOUBLE_HIT("Double Hit"),
	ICY_WIND("Icy Wind"),
	ICE_SHARD("Ice Shard"),
	AQUA_RING("Aqua Ring"),
	AURORA_BEAM("Aurora Beam"),
	BRINE("Brine"),
	DIVE("Dive"),
	ICE_BEAM("Ice Beam"),
	SHEER_COLD("Sheer Cold"),
	POISON_GAS("Poison Gas"),
	SLUDGE("Sludge"),
	SLUDGE_BOMB("Sludge Bomb"),
	ACID_ARMOR("Acid Armor"),
	ICICLE_SPEAR("Icicle Spear"),
	CLAMP("Clamp"),
	RAZOR_SHELL("Razor Shell"),
	WHIRLPOOL("Whirlpool"),
	SHELL_SMASH("Shell Smash"),
	SPIKE_CANNON("Spike Cannon"),
	SPIKES("Spikes"),
	ICICLE_CRASH("Icicle Crash"),
	LICK("Lick"),
	SPITE("Spite"),
	NIGHT_SHADE("Night Shade"),
	SHADOW_BALL("Shadow Ball"),
	DREAM_EATER("Dream Eater"),
	DARK_PULSE("Dark Pulse"),
	NIGHTMARE("Nightmare"),
	SHADOW_PUNCH("Shadow Punch"),
	BIND("Bind"),
	ROCK_TOMB("Rock Tomb"),
	DRAGON_BREATH("Dragon Breath"),
	IRON_TAIL("Iron Tail"),
	MEDITATE("Meditate"),
	SYNCHRONOISE("Synchronoise"),
	PSYSHOCK("Psyshock"),
	VICE_GRIP("Vice Grip"),
	METAL_CLAW("Metal Claw"),
	GUILLOTINE("Guillotine"),
	CRABHAMMER("Crabhammer"),
	FLAIL("Flail"),
	CHARGE("Charge"),
	CHARGE_BEAM("Charge Beam"),
	MIRROR_COAT("Mirror Coat"),
	COUNTER("Counter"),
	BARRAGE("Barrage"),
	BULLET_SEED("Bullet Seed"),
	EGG_BOMB("Egg Bomb"),
	WOOD_HAMMER("Wood Hammer"),
	BONE_CLUB("Bone Club"),
	BONEMERANG("Bonemerang"),
	BONE_RUSH("Bone Rush"),
	ROLLING_KICK("Rolling Kick"),
	JUMP_KICK("Jump Kick"),
	BRICK_BREAK("Brick Break"),
	HIGH_JUMP_KICK("High Jump Kick"),
	BLAZE_KICK("Blaze Kick"),
	MEGA_KICK("Mega Kick"),
	COMET_PUNCH("Comet Punch"),
	MACH_PUNCH("Mach Punch"),
	BULLET_PUNCH("Bullet Punch"),
	VACUUM_WAVE("Vacuum Wave"),
	THUNDER_PUNCH("Thunder Punch"),
	ICE_PUNCH("Ice Punch"),
	FIRE_PUNCH("Fire Punch"),
	SKY_UPPERCUT("Sky Uppercut"),
	MEGA_PUNCH("Mega Punch"),
	FOCUS_PUNCH("Focus Punch"),
	ME_FIRST("Me First"),
	REFRESH("Refresh"),
	POWER_WHIP("Power Whip"),
	SMOG("Smog"),
	CLEAR_SMOG("Clear Smog"),
	HAMMER_ARM("Hammer Arm"),
	SOFT_BOILED("Soft-Boiled"),
	ANCIENT_POWER("Ancient Power"),
	TICKLE("Tickle"),
	DIZZY_PUNCH("Dizzy Punch"),
	OUTRAGE("Outrage"),
	DRAGON_DANCE("Dragon Dance"),
	DRAGON_PULSE("Dragon Pulse"),
	DRACO_METEOR("Draco Meteor"),
	WATERFALL("Waterfall"),
	REFLECT_TYPE("Reflect Type"),
	MAGICAL_LEAF("Magical Leaf"),
	POWER_SWAP("Power Swap"),
	GUARD_SWAP("Guard Swap"),
	COPYCAT("Copycat"),
	TRANSFORM("Transform"),
	SUBSTITUTE("Substitute"),
	RAZOR_WIND("Razor Wind"),
	LOVELY_KISS("Lovely Kiss"),
	POWDER_SNOW("Powder Snow"),
	HEART_STAMP("Heart Stamp"),
	FAKE_TEARS("Fake Tears"),
	AVALANCHE("Avalanche"),
	BLIZZARD("Blizzard"),
	SHOCK_WAVE("Shock Wave"),
	LAVA_PLUME("Lava Plume"),
	WORK_UP("Work Up"),
	GIGA_IMPACT("Giga Impact"),
	SPLASH("Splash"),
	MIST("Mist"),
	LAST_RESORT("Last Resort"),
	TRUMP_CARD("Trump Card"),
	MUDDY_WATER("Muddy Water"),
	CONVERSION("Conversion"),
	CONVERSION2("Conversion 2"),
	SHARPEN("Sharpen"),
	MAGIC_COAT("Magic Coat"),
	SKY_DROP("Sky Drop"),
	IRON_HEAD("Iron Head"),
	ROCK_SLIDE("Rock Slide"),
	SNORE("Snore"),
	SLEEP_TALK("Sleep Talk"),
	BLOCK("Block"),
	SKY_ATTACK("Sky Attack"),
	DRAGON_RUSH("Dragon Rush"),
	AURA_SPHERE("Aura Sphere"),
	PSYSTRIKE("Psystrike"),
	ERUPTION("Eruption"),
	CHARM("Charm"),
	ECHOED_VOICE("Echoed Voice"),
	PSYCHO_SHIFT("Psycho Shift"),
	SHADOW_SNEAK("Shadow Sneak"),
	SPIDER_WEB("Spider Web"),
	SWEET_KISS("Sweet Kiss"),
	OMINOUS_WIND("Ominous Wind"),
	COTTON_SPORE("Cotton Spore"),
	COTTON_GUARD("Cotton Guard"),
	GRASS_WHISTLE("Grass Whistle"),
	TORMENT("Torment"),
	HIDDEN_POWER("Hidden Power"),
	PSYWAVE("Psywave"),
	PAIN_SPLIT("Pain Split"),
	BIDE("Bide"),
	AUTOTOMIZE("Autotomize"),
	STRUGGLE_BUG("Struggle Bug"),
	POWER_TRICK("Power Trick"),
	POWER_SPLIT("Power Split"),
	GUARD_SPLIT("Guard Split"),
	HONE_CLAWS("Hone Claws"),
	BEAT_UP("Beat Up"),
	OCTAZOOKA("Octazooka"),
	PRESENT("Present"),
	STEEL_WING("Steel Wing"),
	SKETCH("Sketch"),
	TRIPLE_KICK("Triple Kick"),
	MILK_DRINK("Milk Drink"),
	HEAL_BELL("Heal Bell"),
	WEATHER_BALL("Weather Ball"),
	AEROBLAST("Aeroblast"),
	SACRED_FIRE("Sacred Fire"),
	HEAL_BLOCK("Heal Block"),
	ENERGY_BALL("Energy Ball"),
	BULK_UP("Bulk Up"),
	THIEF("Thief"),
	ATTRACT("Attract"),
	FORCE_PALM("Force Palm"),
	ARM_THRUST("Arm Thrust"),
	SMELLING_SALTS("Smelling Salts"),
	ASSIST("Assist"),
	METAL_BURST("Metal Burst"),
	WILD_CHARGE("Wild Charge"),
	FLASH("Flash"),
	TAIL_GLOW("Tail Glow"),
	WATER_SPOUT("Water Spout"),
	TEETER_DANCE("Teeter Dance"),
	NEEDLE_ARM("Needle Arm"),
	VENOSHOCK("Venoshock"),
	SNATCH("Snatch"),
	ICE_BALL("Ice Ball"),
	HEAD_SMASH("Head Smash"),
	MIST_BALL("Mist Ball"),
	LUSTER_PURGE("Luster Purge"),
	PSYCHO_BOOST("Psycho Boost"),
	FACADE("Facade"),
	DEFEND_ORDER("Defend Order"),
	HEAL_ORDER("Heal Order"),
	ATTACK_ORDER("Attack Order"),
	CHATTER("Chatter"),
	DUAL_CHOP("Dual Chop"),
	ROCK_WRECKER("Rock Wrecker"),
	TRICK_ROOM("Trick Room"),
	ROAR_OF_TIME("Roar Of Time"),
	SPACIAL_REND("Spacial Rend"),
	MAGMA_STORM("Magma Storm"),
	CRUSH_GRIP("Crush Grip"),
	SHADOW_FORCE("Shadow Force"),
	HEART_SWAP("Heart Swap"),
	DARK_VOID("Dark Void"),
	SEED_FLARE("Seed Flare"),
	JUDGEMENT("Judgement"),
	SEARING_SHOT("Searing Shot"),
	INCINERATE("Incinerate"),
	OVERHEAT("Overheat"),
	HEAT_CRASH("Heat Crash"),
	GRASS_KNOT("Grass Knot"),
	SCALD("Scald"),
	DRAIN_PUNCH("Drain Punch"),
	STORM_THROW("Storm Throw"),
	FROST_BREATH("Frost Breath"),
	ROCK_SMASH("Rock Smash"),
	ROCK_CLIMB("Rock Climb"),
	NIGHT_DAZE("Night Daze"),
	TAIL_SLAP("Tail Slap"),
	DEFOG("Defog"),
	HORN_LEECH("Horn Leech"),
	ELECTROWEB("Electroweb"),
	GEAR_GRIND("Gear Grind"),
	SHIFT_GEAR("Shift Gear"),
	HEAD_CHARGE("Head Charge"),
	FIERY_DANCE("Fiery Dance"),
	SACRED_SWORD("Sacred Sword"),
	SECRET_SWORD("Secret Sword"),
	FUSION_FLARE("Fusion Flare"),
	FUSION_BOLT("Fusion Bolt"),
	BLUE_FLARE("Blue Flare"),
	BOLT_STRIKE("Bolt Strike"),
	GLACIATE("Glaciate"),
	TECHNO_BLAST("Techno Blast"),
	EXPLOSION("Explosion"),
	SELF_DESTRUCT("Self-Destruct"),
	FLING("Fling"),
	FREEZE_SHOCK("Freeze Shock"),
	SECRET_POWER("Secret Power"),
	FINAL_GAMBIT("Final Gambit"),
	GASTRO_ACID("Gastro Acid"),
	HEALING_WISH("Healing Wish"),
	LUNAR_DANCE("Lunar Dance"),
	ROAR("Roar"),
	GRUDGE("Grudge"),
	RETALIATE("Retaliate"),
	CIRCLE_THROW("Circle Throw"),
	TELEPORT("Teleport"),
	ROLE_PLAY("Role Play"),
	KNOCK_OFF("Knock Off"),
	WHIRLWIND("Whirlwind"),
	BESTOW("Bestow"),
	SWITCHEROO("Switcheroo"),
	TRICK("Trick"),
	MEMENTO("Memento"),
	DESTINY_BOND("Destiny Bond"),
	CAMOUFLAGE("Camouflage"),
	RECYCLE("Recycle"),
	PARTING_SHOT("Parting Shot"),
	U_TURN("U-turn"),
	BATON_PASS("Baton Pass"),
	PERISH_SONG("Perish Song"),
	DRAGON_TAIL("Dragon Tail"),
	FOUL_PLAY("Foul Play"),
	EMBARGO("Embargo"),
	NATURE_POWER("Nature Power"),
	ENTRAINMENT("Entrainment"),
	MAGIC_ROOM("Magic Room"),
	WORRY_SEED("Worry Seed"),
	SIMPLE_BEAM("Simple Beam"),
	SKILL_SWAP("Skill Swap"),
	VOLT_SWITCH("Volt Switch"),
	RELIC_SONG("Relic Song"),
	SNARL("Snarl"),
	ICE_BURN("Ice Burn"),
	V_CREATE("V-create"),
	SURF("Surf"),
	VOLT_TACKLE("Volt Tackle"),
	FOCUS_BLAST("Focus Blast"),
	DIAMOND_STORM("Diamond Storm"),
	MOONBLAST("Moonblast"),
	LANDS_WRATH("Land's Wrath"),
	PHANTOM_FORCE("Phantom Force"),
	OBLIVION_WING("Oblivion Wing"),
	GEOMANCY("Geomancy"),
	BOOMBURST("Boomburst"),
	PLAY_ROUGH("Play Rough"),
	CRAFTY_SHIELD("Crafty Shield"),
	NUZZLE("Nuzzle"),
	DRAINING_KISS("Draining Kiss"),
	FAIRY_WIND("Fairy Wind"),
	PARABOLIC_CHARGE("Parabolic Charge"),
	DISARMING_VOICE("Disarming Voice"),
	FREEZE_DRY("Freeze-Dry"),
	FLYING_PRESS("Flying Press"),
	TOPSY_TURVY("Topsy-Turvy"),
	PLAY_NICE("Play Nice"),
	EERIE_IMPULSE("Eerie Impulse"),
	MISTY_TERRAIN("Misty Terrain"),
	FAIRY_LOCK("Fairy Lock"),
	AROMATIC_MIST("Aromatic Mist"),
	BABY_DOLL_EYES("Baby-Doll Eyes"),
	PETAL_BLIZZARD("Petal Blizzard"),
	GRASSY_TERRAIN("Grassy Terrain"),
	FLOWER_SHIELD("Flower Shield"),
	NOBLE_ROAR("Noble Roar"),
	POWDER("Powder"),
	ROTOTILLER("Rototiller"),
	WATER_SHURIKEN("Water Shuriken"),
	MAT_BLOCK("Mat Block"),
	MYSTICAL_FIRE("Mystical Fire"),
	INFESTATION("Infestation"),
	ELECTRIFY("Electrify"),
	FELL_STINGER("Fell Stinger"),
	MAGNETIC_FLUX("Magnetic Flux"),
	STICKY_WEB("Sticky Web"),
	BELCH("Belch"),
	VENOM_DRENCH("Venom Drench"),
	ELECTRIC_TERRAIN("Electric Terrain"),
	POWER_UP_PUNCH("Power-Up Punch"),
	CONFIDE("Confide"),
	CUT("Cut"),
	DAZZLING_GLEAM("Dazzling Gleam"),
	STRENGTH("Strength"),
	ORIGIN_PULSE("Origin Pulse"),
	PRECIPICE_BLADES("Precipice Blades");

    // EVERYTHING ABOVE IS GENERATED ###

    private String name;

    AttackNamesies(String name) {
        this.name = name;
    }

    public String getName() {
		return this.name;
	}

	public static AttackNamesies getValueOf(String name) {
		try {
			return AttackNamesies.valueOf(PokeString.getNamesiesString(name));
		} catch (IllegalArgumentException exception) {
			Global.error(name + " does not have a valid AttackNamesies value");
			return null;
		}
	}
}

