package namesies;

import main.Global;
import util.PokeString;

public enum ItemNamesies {
    // EVERYTHING BELOW IS GENERATED ###
	NO_ITEM("No Item"),
	SYRUP("Syrup"),
	BICYCLE("Bicycle"),
	SURFBOARD("Surfboard"),
	FISHING_ROD("Fishing Rod"),
	ABSORB_BULB("Absorb Bulb"),
	AIR_BALLOON("Air Balloon"),
	AMULET_COIN("Amulet Coin"),
	BIG_ROOT("Big Root"),
	BINDING_BAND("Binding Band"),
	BLACK_SLUDGE("Black Sludge"),
	BRIGHT_POWDER("Bright Powder"),
	CELL_BATTERY("Cell Battery"),
	CHOICE_BAND("Choice Band"),
	CHOICE_SCARF("Choice Scarf"),
	CHOICE_SPECS("Choice Specs"),
	CLEANSE_TAG("Cleanse Tag"),
	DAMP_ROCK("Damp Rock"),
	HEAT_ROCK("Heat Rock"),
	ICY_ROCK("Icy Rock"),
	SMOOTH_ROCK("Smooth Rock"),
	EJECT_BUTTON("Eject Button"),
	DESTINY_KNOT("Destiny Knot"),
	EXPERT_BELT("Expert Belt"),
	FLAME_ORB("Flame Orb"),
	TOXIC_ORB("Toxic Orb"),
	FLOAT_STONE("Float Stone"),
	FOCUS_BAND("Focus Band"),
	FOCUS_SASH("Focus Sash"),
	GRIP_CLAW("Grip Claw"),
	ADAMANT_ORB("Adamant Orb"),
	LUSTROUS_ORB("Lustrous Orb"),
	GRISEOUS_ORB("Griseous Orb"),
	IRON_BALL("Iron Ball"),
	LAGGING_TAIL("Lagging Tail"),
	LIFE_ORB("Life Orb"),
	LIGHT_BALL("Light Ball"),
	LIGHT_CLAY("Light Clay"),
	LUCKY_EGG("Lucky Egg"),
	LUCKY_PUNCH("Lucky Punch"),
	LUMINOUS_MOSS("Luminous Moss"),
	MACHO_BRACE("Macho Brace"),
	MENTAL_HERB("Mental Herb"),
	METAL_POWDER("Metal Powder"),
	METRONOME("Metronome"),
	MUSCLE_BAND("Muscle Band"),
	POWER_ANKLET("Power Anklet"),
	POWER_BAND("Power Band"),
	POWER_BELT("Power Belt"),
	POWER_BRACER("Power Bracer"),
	POWER_LENS("Power Lens"),
	POWER_WEIGHT("Power Weight"),
	QUICK_CLAW("Quick Claw"),
	QUICK_POWDER("Quick Powder"),
	RED_CARD("Red Card"),
	RING_TARGET("Ring Target"),
	ROCKY_HELMET("Rocky Helmet"),
	SAFETY_GOGGLES("Safety Goggles"),
	SCOPE_LENS("Scope Lens"),
	SHED_SHELL("Shed Shell"),
	SHELL_BELL("Shell Bell"),
	SMOKE_BALL("Smoke Ball"),
	SNOWBALL("Snowball"),
	SOUL_DEW("Soul Dew"),
	STICK("Stick"),
	STICKY_BARB("Sticky Barb"),
	THICK_CLUB("Thick Club"),
	WEAKNESS_POLICY("Weakness Policy"),
	WHITE_HERB("White Herb"),
	WIDE_LENS("Wide Lens"),
	WISE_GLASSES("Wise Glasses"),
	ZOOM_LENS("Zoom Lens"),
	FULL_INCENSE("Full Incense"),
	LAX_INCENSE("Lax Incense"),
	LUCK_INCENSE("Luck Incense"),
	ODD_INCENSE("Odd Incense"),
	PURE_INCENSE("Pure Incense"),
	ROCK_INCENSE("Rock Incense"),
	ROSE_INCENSE("Rose Incense"),
	SEA_INCENSE("Sea Incense"),
	WAVE_INCENSE("Wave Incense"),
	DRACO_PLATE("Draco Plate"),
	DREAD_PLATE("Dread Plate"),
	EARTH_PLATE("Earth Plate"),
	FIST_PLATE("Fist Plate"),
	FLAME_PLATE("Flame Plate"),
	ICICLE_PLATE("Icicle Plate"),
	INSECT_PLATE("Insect Plate"),
	IRON_PLATE("Iron Plate"),
	MEADOW_PLATE("Meadow Plate"),
	MIND_PLATE("Mind Plate"),
	PIXIE_PLATE("Pixie Plate"),
	SKY_PLATE("Sky Plate"),
	SPLASH_PLATE("Splash Plate"),
	SPOOKY_PLATE("Spooky Plate"),
	STONE_PLATE("Stone Plate"),
	TOXIC_PLATE("Toxic Plate"),
	ZAP_PLATE("Zap Plate"),
	BURN_DRIVE("Burn Drive"),
	CHILL_DRIVE("Chill Drive"),
	DOUSE_DRIVE("Douse Drive"),
	SHOCK_DRIVE("Shock Drive"),
	FIRE_GEM("Fire Gem"),
	WATER_GEM("Water Gem"),
	ELECTRIC_GEM("Electric Gem"),
	GRASS_GEM("Grass Gem"),
	ICE_GEM("Ice Gem"),
	FIGHTING_GEM("Fighting Gem"),
	POISON_GEM("Poison Gem"),
	GROUND_GEM("Ground Gem"),
	FLYING_GEM("Flying Gem"),
	PSYCHIC_GEM("Psychic Gem"),
	BUG_GEM("Bug Gem"),
	ROCK_GEM("Rock Gem"),
	GHOST_GEM("Ghost Gem"),
	DRAGON_GEM("Dragon Gem"),
	DARK_GEM("Dark Gem"),
	STEEL_GEM("Steel Gem"),
	NORMAL_GEM("Normal Gem"),
	FAIRY_GEM("Fairy Gem"),
	LEFTOVERS("Leftovers"),
	BLACK_BELT("Black Belt"),
	BLACK_GLASSES("Black Glasses"),
	CHARCOAL("Charcoal"),
	DRAGON_FANG("Dragon Fang"),
	HARD_STONE("Hard Stone"),
	MAGNET("Magnet"),
	METAL_COAT("Metal Coat"),
	MIRACLE_SEED("Miracle Seed"),
	MYSTIC_WATER("Mystic Water"),
	NEVER_MELT_ICE("NeverMeltIce"),
	POISON_BARB("Poison Barb"),
	SHARP_BEAK("Sharp Beak"),
	SILK_SCARF("Silk Scarf"),
	SILVER_POWDER("Silver Powder"),
	SOFT_SAND("Soft Sand"),
	SPELL_TAG("Spell Tag"),
	TWISTED_SPOON("Twisted Spoon"),
	DAWN_STONE("Dawn Stone"),
	DEEP_SEA_SCALE("Deep Sea Scale"),
	DEEP_SEA_TOOTH("Deep Sea Tooth"),
	DRAGON_SCALE("Dragon Scale"),
	DUBIOUS_DISC("Dubious Disc"),
	DUSK_STONE("Dusk Stone"),
	ELECTIRIZER("Electirizer"),
	FIRE_STONE("Fire Stone"),
	KINGS_ROCK("King's Rock"),
	LEAF_STONE("Leaf Stone"),
	MAGMARIZER("Magmarizer"),
	MOON_STONE("Moon Stone"),
	OVAL_STONE("Oval Stone"),
	EVERSTONE("Everstone"),
	PRISM_SCALE("Prism Scale"),
	PROTECTOR("Protector"),
	RAZOR_CLAW("Razor Claw"),
	RAZOR_FANG("Razor Fang"),
	REAPER_CLOTH("Reaper Cloth"),
	SACHET("Sachet"),
	SHINY_STONE("Shiny Stone"),
	SUN_STONE("Sun Stone"),
	THUNDER_STONE("Thunder Stone"),
	UP_GRADE("Up-Grade"),
	WATER_STONE("Water Stone"),
	WHIPPED_DREAM("Whipped Dream"),
	ANTIDOTE("Antidote"),
	AWAKENING("Awakening"),
	BURN_HEAL("Burn Heal"),
	ICE_HEAL("Ice Heal"),
	PARALYZE_HEAL("Paralyze Heal"),
	FULL_HEAL("Full Heal"),
	FULL_RESTORE("Full Restore"),
	ELIXIR("Elixir"),
	MAX_ELIXIR("Max Elixir"),
	ETHER("Ether"),
	MAX_ETHER("Max Ether"),
	BERRY_JUICE("Berry Juice"),
	SWEET_HEART("Sweet Heart"),
	POTION("Potion"),
	ENERGY_POWDER("Energy Powder"),
	FRESH_WATER("Fresh Water"),
	SUPER_POTION("Super Potion"),
	SODA_POP("Soda Pop"),
	LEMONADE("Lemonade"),
	MOOMOO_MILK("Moomoo Milk"),
	ENERGY_ROOT("Energy Root"),
	HYPER_POTION("Hyper Potion"),
	MAX_POTION("Max Potion"),
	REVIVE("Revive"),
	MAX_REVIVE("Max Revive"),
	REVIVAL_HERB("Revival Herb"),
	SACRED_ASH("Sacred Ash"),
	DIRE_HIT("Dire Hit"),
	GUARD_SPEC("Guard Spec."),
	XACCURACY("X Accuracy"),
	XATTACK("X Attack"),
	XDEFEND("X Defend"),
	XSPECIAL("X Special"),
	XSP_DEF("X Sp. Def"),
	XSPEED("X Speed"),
	HPUP("HP Up"),
	PROTEIN("Protein"),
	IRON("Iron"),
	CALCIUM("Calcium"),
	ZINC("Zinc"),
	CARBOS("Carbos"),
	HEALTH_WING("Health Wing"),
	MUSCLE_WING("Muscle Wing"),
	RESIST_WING("Resist Wing"),
	GENIUS_WING("Genius Wing"),
	CLEVER_WING("Clever Wing"),
	SWIFT_WING("Swift Wing"),
	PPMAX("PP Max"),
	PPUP("PP Up"),
	RARE_CANDY("Rare Candy"),
	CHERISH_BALL("Cherish Ball"),
	DIVE_BALL("Dive Ball"),
	DUSK_BALL("Dusk Ball"),
	FAST_BALL("Fast Ball"),
	GREAT_BALL("Great Ball"),
	HEAL_BALL("Heal Ball"),
	HEAVY_BALL("Heavy Ball"),
	LEVEL_BALL("Level Ball"),
	LOVE_BALL("Love Ball"),
	LURE_BALL("Lure Ball"),
	LUXURY_BALL("Luxury Ball"),
	MASTER_BALL("Master Ball"),
	MOON_BALL("Moon Ball"),
	NEST_BALL("Nest Ball"),
	NET_BALL("Net Ball"),
	POKE_BALL("Pok\u00e9 Ball"),
	PREMIER_BALL("Premier Ball"),
	QUICK_BALL("Quick Ball"),
	REPEAT_BALL("Repeat Ball"),
	SAFARI_BALL("Safari Ball"),
	TIMER_BALL("Timer Ball"),
	ULTRA_BALL("Ultra Ball"),
	CHERI_BERRY("Cheri Berry"),
	CHESTO_BERRY("Chesto Berry"),
	PECHA_BERRY("Pecha Berry"),
	RAWST_BERRY("Rawst Berry"),
	ASPEAR_BERRY("Aspear Berry"),
	LEPPA_BERRY("Leppa Berry"),
	ORAN_BERRY("Oran Berry"),
	PERSIM_BERRY("Persim Berry"),
	LUM_BERRY("Lum Berry"),
	SITRUS_BERRY("Sitrus Berry"),
	RAZZ_BERRY("Razz Berry"),
	POMEG_BERRY("Pomeg Berry"),
	KELPSY_BERRY("Kelpsy Berry"),
	QUALOT_BERRY("Qualot Berry"),
	HONDEW_BERRY("Hondew Berry"),
	GREPA_BERRY("Grepa Berry"),
	TAMATO_BERRY("Tamato Berry"),
	OCCA_BERRY("Occa Berry"),
	PASSHO_BERRY("Passho Berry"),
	WACAN_BERRY("Wacan Berry"),
	RINDO_BERRY("Rindo Berry"),
	YACHE_BERRY("Yache Berry"),
	CHOPLE_BERRY("Chople Berry"),
	KEBIA_BERRY("Kebia Berry"),
	SHUCA_BERRY("Shuca Berry"),
	COBA_BERRY("Coba Berry"),
	PAYAPA_BERRY("Payapa Berry"),
	TANGA_BERRY("Tanga Berry"),
	CHARTI_BERRY("Charti Berry"),
	KASIB_BERRY("Kasib Berry"),
	HABAN_BERRY("Haban Berry"),
	COLBUR_BERRY("Colbur Berry"),
	BABIRI_BERRY("Babiri Berry"),
	CHILAN_BERRY("Chilan Berry"),
	ROSELI_BERRY("Roseli Berry"),
	LIECHI_BERRY("Liechi Berry"),
	GANLON_BERRY("Ganlon Berry"),
	SALAC_BERRY("Salac Berry"),
	PETAYA_BERRY("Petaya Berry"),
	APICOT_BERRY("Apicot Berry"),
	MICLE_BERRY("Micle Berry"),
	KEE_BERRY("Kee Berry"),
	MARANGA_BERRY("Maranga Berry"),
	JABOCA_BERRY("Jaboca Berry"),
	ROWAP_BERRY("Rowap Berry"),
	CUSTAP_BERRY("Custap Berry"),
	ENIGMA_BERRY("Enigma Berry"),
	LANSAT_BERRY("Lansat Berry"),
	STARF_BERRY("Starf Berry"),
	COMET_SHARD("Comet Shard"),
	TINY_MUSHROOM("Tiny Mushroom"),
	BIG_MUSHROOM("Big Mushroom"),
	BALM_MUSHROOM("Balm Mushroom"),
	NUGGET("Nugget"),
	BIG_NUGGET("Big Nugget"),
	PEARL("Pearl"),
	BIG_PEARL("Big Pearl"),
	STARDUST("Stardust"),
	STAR_PIECE("Star Piece"),
	RARE_BONE("Rare Bone"),
	HONEY("Honey"),
	EVIOLITE("Eviolite"),
	HEART_SCALE("Heart Scale"),
	REPEL("Repel"),
	SUPER_REPEL("Super Repel"),
	MAX_REPEL("Max Repel"),
	ABILITY_CAPSULE("Ability Capsule"),
	ASSAULT_VEST("Assault Vest"),
	POWER_HERB("Power Herb"),
	HONE_CLAWS_TM("Hone Claws TM"),
	DRAGON_CLAW_TM("Dragon Claw TM"),
	PSYSHOCK_TM("Psyshock TM"),
	CALM_MIND_TM("Calm Mind TM"),
	ROAR_TM("Roar TM"),
	TOXIC_TM("Toxic TM"),
	HAIL_TM("Hail TM"),
	BULK_UP_TM("Bulk Up TM"),
	VENOSHOCK_TM("Venoshock TM"),
	HIDDEN_POWER_TM("Hidden Power TM"),
	SUNNY_DAY_TM("Sunny Day TM"),
	TAUNT_TM("Taunt TM"),
	ICE_BEAM_TM("Ice Beam TM"),
	BLIZZARD_TM("Blizzard TM"),
	HYPER_BEAM_TM("Hyper Beam TM"),
	LIGHT_SCREEN_TM("Light Screen TM"),
	PROTECT_TM("Protect TM"),
	RAIN_DANCE_TM("Rain Dance TM"),
	ROOST_TM("Roost TM"),
	SAFEGUARD_TM("Safeguard TM"),
	SOLAR_BEAM_TM("Solar Beam TM"),
	SMACK_DOWN_TM("Smack Down TM"),
	THUNDERBOLT_TM("Thunderbolt TM"),
	THUNDER_TM("Thunder TM"),
	EARTHQUAKE_TM("Earthquake TM"),
	DIG_TM("Dig TM"),
	PSYCHIC_TM("Psychic TM"),
	SHADOW_BALL_TM("Shadow Ball TM"),
	BRICK_BREAK_TM("Brick Break TM"),
	DOUBLE_TEAM_TM("Double Team TM"),
	REFLECT_TM("Reflect TM"),
	SLUDGE_WAVE_TM("Sludge Wave TM"),
	FLAMETHROWER_TM("Flamethrower TM"),
	SLUDGE_BOMB_TM("Sludge Bomb TM"),
	SANDSTORM_TM("Sandstorm TM"),
	FIRE_BLAST_TM("Fire Blast TM"),
	ROCK_TOMB_TM("Rock Tomb TM"),
	AERIAL_ACE_TM("Aerial Ace TM"),
	TORMENT_TM("Torment TM"),
	FACADE_TM("Facade TM"),
	FLAME_CHARGE_TM("Flame Charge TM"),
	REST_TM("Rest TM"),
	ATTRACT_TM("Attract TM"),
	THIEF_TM("Thief TM"),
	LOW_SWEEP_TM("Low Sweep TM"),
	ROUND_TM("Round TM"),
	ECHOED_VOICE_TM("Echoed Voice TM"),
	OVERHEAT_TM("Overheat TM"),
	STEEL_WING_TM("Steel Wing TM"),
	FOCUS_BLAST_TM("Focus Blast TM"),
	ENERGY_BALL_TM("Energy Ball TM"),
	FALSE_SWIPE_TM("False Swipe TM"),
	SCALD_TM("Scald TM"),
	FLING_TM("Fling TM"),
	CHARGE_BEAM_TM("Charge Beam TM"),
	SKY_DROP_TM("Sky Drop TM"),
	INCINERATE_TM("Incinerate TM"),
	WILL_O_WISP_TM("Will-O-Wisp TM"),
	ACROBATICS_TM("Acrobatics TM"),
	EMBARGO_TM("Embargo TM"),
	EXPLOSION_TM("Explosion TM"),
	SHADOW_CLAW_TM("Shadow Claw TM"),
	PAYBACK_TM("Payback TM"),
	RETALIATE_TM("Retaliate TM"),
	GIGA_IMPACT_TM("Giga Impact TM"),
	ROCK_POLISH_TM("Rock Polish TM"),
	FLASH_TM("Flash TM"),
	STONE_EDGE_TM("Stone Edge TM"),
	VOLT_SWITCH_TM("Volt Switch TM"),
	THUNDER_WAVE_TM("Thunder Wave TM"),
	GYRO_BALL_TM("Gyro Ball TM"),
	SWORDS_DANCE_TM("Swords Dance TM"),
	STRUGGLE_BUG_TM("Struggle Bug TM"),
	PSYCH_UP_TM("Psych Up TM"),
	BULLDOZE_TM("Bulldoze TM"),
	FROST_BREATH_TM("Frost Breath TM"),
	ROCK_SLIDE_TM("Rock Slide TM"),
	X_SCISSOR_TM("X-Scissor TM"),
	DRAGON_TAIL_TM("Dragon Tail TM"),
	INFESTATION_TM("Infestation TM"),
	POISON_JAB_TM("Poison Jab TM"),
	DREAM_EATER_TM("Dream Eater TM"),
	GRASS_KNOT_TM("Grass Knot TM"),
	SWAGGER_TM("Swagger TM"),
	SLEEP_TALK_TM("Sleep Talk TM"),
	U_TURN_TM("U-turn TM"),
	SUBSTITUTE_TM("Substitute TM"),
	FLASH_CANNON_TM("Flash Cannon TM"),
	TRICK_ROOM_TM("Trick Room TM"),
	WILD_CHARGE_TM("Wild Charge TM"),
	ROCK_SMASH_TM("Rock Smash TM"),
	SNARL_TM("Snarl TM"),
	NATURE_POWER_TM("Nature Power TM"),
	DARK_PULSE_TM("Dark Pulse TM"),
	POWER_UP_PUNCH_TM("Power-Up Punch TM"),
	DAZZLING_GLEAM_TM("Dazzling Gleam TM"),
	CONFIDE_TM("Confide TM"),
	CUT_TM("Cut TM"),
	FLY_TM("Fly TM"),
	SURF_TM("Surf TM"),
	STRENGTH_TM("Strength TM"),
	WATERFALL_TM("Waterfall TM");

    // EVERYTHING ABOVE IS GENERATED ###

    private String name;

    ItemNamesies(String name) {
        this.name = name;
    }

	public String getName() {
		return this.name;
	}

	public static ItemNamesies getValueOf(String name) {
		try {
			return ItemNamesies.valueOf(PokeString.getNamesiesString(name));
		} catch (IllegalArgumentException exception) {
			Global.error(name + " does not have a valid ItemNamesies value");
			return null;
		}
	}
}

