package main;

public enum Namesies
{
	// EVERYTHING BELOW IS GENERATED ###
	TACKLE_ATTACK("Tackle"),
	LEECH_SEED_ATTACK("Leech Seed"),
	THUNDER_WAVE_ATTACK("Thunder Wave"),
	POISON_POWDER_ATTACK("Poison Powder"),
	SLEEP_POWDER_ATTACK("Sleep Powder"),
	TOXIC_ATTACK("Toxic"),
	EMBER_ATTACK("Ember"),
	GROWL_ATTACK("Growl"),
	SCRATCH_ATTACK("Scratch"),
	VINE_WHIP_ATTACK("Vine Whip"),
	SONIC_BOOM_ATTACK("Sonic Boom"),
	SMOKESCREEN_ATTACK("Smokescreen"),
	TAKE_DOWN_ATTACK("Take Down"),
	STRUGGLE_ATTACK("Struggle"),
	RAZOR_LEAF_ATTACK("Razor Leaf"),
	SWEET_SCENT_ATTACK("Sweet Scent"),
	GROWTH_ATTACK("Growth"),
	DOUBLE_EDGE_ATTACK("Double-edge"),
	SEED_BOMB_ATTACK("Seed Bomb"),
	SYNTHESIS_ATTACK("Synthesis"),
	RECOVER_ATTACK("Recover"),
	DRAGON_RAGE_ATTACK("Dragon Rage"),
	SCARY_FACE_ATTACK("Scary Face"),
	FIRE_FANG_ATTACK("Fire Fang"),
	FLAME_BURST_ATTACK("Flame Burst"),
	BITE_ATTACK("Bite"),
	SLASH_ATTACK("Slash"),
	TAIL_WHIP_ATTACK("Tail Whip"),
	SOLAR_BEAM_ATTACK("Solar Beam"),
	FLAMETHROWER_ATTACK("Flamethrower"),
	FLY_ATTACK("Fly"),
	FIRE_SPIN_ATTACK("Fire Spin"),
	INFERNO_ATTACK("Inferno"),
	DRAGON_CLAW_ATTACK("Dragon Claw"),
	SHADOW_CLAW_ATTACK("Shadow Claw"),
	AIR_SLASH_ATTACK("Air Slash"),
	WING_ATTACK_ATTACK("Wing Attack"),
	HEAT_WAVE_ATTACK("Heat Wave"),
	FLARE_BLITZ_ATTACK("Flare Blitz"),
	FLASH_CANNON_ATTACK("Flash Cannon"),
	BUBBLE_ATTACK("Bubble"),
	WITHDRAW_ATTACK("Withdraw"),
	WATER_GUN_ATTACK("Water Gun"),
	RAPID_SPIN_ATTACK("Rapid Spin"),
	REFLECT_ATTACK("Reflect"),
	PROTECT_ATTACK("Protect"),
	DETECT_ATTACK("Detect"),
	QUICK_GUARD_ATTACK("Quick Guard"),
	ENDURE_ATTACK("Endure"),
	WATER_PULSE_ATTACK("Water Pulse"),
	CONFUSION_DAMAGE_ATTACK("ConfusionDamage"),
	CONFUSE_RAY_ATTACK("Confuse Ray"),
	AQUA_TAIL_ATTACK("Aqua Tail"),
	SKULL_BASH_ATTACK("Skull Bash"),
	IRON_DEFENSE_ATTACK("Iron Defense"),
	HYDRO_PUMP_ATTACK("Hydro Pump"),
	RAIN_DANCE_ATTACK("Rain Dance"),
	SUNNY_DAY_ATTACK("Sunny Day"),
	SANDSTORM_ATTACK("Sandstorm"),
	HAIL_ATTACK("Hail"),
	PETAL_DANCE_ATTACK("Petal Dance"),
	THRASH_ATTACK("Thrash"),
	HYPER_BEAM_ATTACK("Hyper Beam"),
	STRING_SHOT_ATTACK("String Shot"),
	BUG_BITE_ATTACK("Bug Bite"),
	HARDEN_ATTACK("Harden"),
	CONFUSION_ATTACK("Confusion"),
	STUN_SPORE_ATTACK("Stun Spore"),
	GUST_ATTACK("Gust"),
	SUPERSONIC_ATTACK("Supersonic"),
	PSYBEAM_ATTACK("Psybeam"),
	SILVER_WIND_ATTACK("Silver Wind"),
	TAILWIND_ATTACK("Tailwind"),
	MORNING_SUN_ATTACK("Morning Sun"),
	SAFEGUARD_ATTACK("Safeguard"),
	CAPTIVATE_ATTACK("Captivate"),
	BUG_BUZZ_ATTACK("Bug Buzz"),
	QUIVER_DANCE_ATTACK("Quiver Dance"),
	ENCORE_ATTACK("Encore"),
	POISON_STING_ATTACK("Poison Sting"),
	FURY_ATTACK_ATTACK("Fury Attack"),
	FALSE_SWIPE_ATTACK("False Swipe"),
	DISABLE_ATTACK("Disable"),
	FOCUS_ENERGY_ATTACK("Focus Energy"),
	TWINEEDLE_ATTACK("Twineedle"),
	RAGE_ATTACK("Rage"),
	PURSUIT_ATTACK("Pursuit"),
	TOXIC_SPIKES_ATTACK("Toxic Spikes"),
	PIN_MISSILE_ATTACK("Pin Missile"),
	AGILITY_ATTACK("Agility"),
	ASSURANCE_ATTACK("Assurance"),
	POISON_JAB_ATTACK("Poison Jab"),
	ENDEAVOR_ATTACK("Endeavor"),
	SAND_ATTACK_ATTACK("Sand Attack"),
	QUICK_ATTACK_ATTACK("Quick Attack"),
	TWISTER_ATTACK("Twister"),
	FEATHER_DANCE_ATTACK("Feather Dance"),
	ROOST_ATTACK("Roost"),
	THUNDER_SHOCK_ATTACK("Thunder Shock"),
	MIRROR_MOVE_ATTACK("Mirror Move"),
	HURRICANE_ATTACK("Hurricane"),
	HYPER_FANG_ATTACK("Hyper Fang"),
	SUCKER_PUNCH_ATTACK("Sucker Punch"),
	CRUNCH_ATTACK("Crunch"),
	SUPER_FANG_ATTACK("Super Fang"),
	SWORDS_DANCE_ATTACK("Swords Dance"),
	PECK_ATTACK("Peck"),
	LEER_ATTACK("Leer"),
	AERIAL_ACE_ATTACK("Aerial Ace"),
	DRILL_PECK_ATTACK("Drill Peck"),
	PLUCK_ATTACK("Pluck"),
	DRILL_RUN_ATTACK("Drill Run"),
	WRAP_ATTACK("Wrap"),
	GLARE_ATTACK("Glare"),
	SCREECH_ATTACK("Screech"),
	ACID_ATTACK("Acid"),
	STOCKPILE_ATTACK("Stockpile"),
	SPIT_UP_ATTACK("Spit Up"),
	SWALLOW_ATTACK("Swallow"),
	ACID_SPRAY_ATTACK("Acid Spray"),
	MUD_BOMB_ATTACK("Mud Bomb"),
	HAZE_ATTACK("Haze"),
	COIL_ATTACK("Coil"),
	GUNK_SHOT_ATTACK("Gunk Shot"),
	ICE_FANG_ATTACK("Ice Fang"),
	THUNDER_FANG_ATTACK("Thunder Fang"),
	ELECTRO_BALL_ATTACK("Electro Ball"),
	DOUBLE_TEAM_ATTACK("Double Team"),
	SLAM_ATTACK("Slam"),
	THUNDERBOLT_ATTACK("Thunderbolt"),
	FEINT_ATTACK("Feint"),
	DISCHARGE_ATTACK("Discharge"),
	LIGHT_SCREEN_ATTACK("Light Screen"),
	THUNDER_ATTACK("Thunder"),
	DEFENSE_CURL_ATTACK("Defense Curl"),
	SWIFT_ATTACK("Swift"),
	FURY_SWIPES_ATTACK("Fury Swipes"),
	ROLLOUT_ATTACK("Rollout"),
	FURY_CUTTER_ATTACK("Fury Cutter"),
	SAND_TOMB_ATTACK("Sand Tomb"),
	GYRO_BALL_ATTACK("Gyro Ball"),
	CRUSH_CLAW_ATTACK("Crush Claw"),
	DOUBLE_KICK_ATTACK("Double Kick"),
	POISON_TAIL_ATTACK("Poison Tail"),
	FLATTER_ATTACK("Flatter"),
	POISON_FANG_ATTACK("Poison Fang"),
	CHIP_AWAY_ATTACK("Chip Away"),
	BODY_SLAM_ATTACK("Body Slam"),
	EARTH_POWER_ATTACK("Earth Power"),
	SUPERPOWER_ATTACK("Superpower"),
	HORN_ATTACK_ATTACK("Horn Attack"),
	HORN_DRILL_ATTACK("Horn Drill"),
	MEGAHORN_ATTACK("Megahorn"),
	POUND_ATTACK("Pound"),
	SING_ATTACK("Sing"),
	DOUBLE_SLAP_ATTACK("Double Slap"),
	WISH_ATTACK("Wish"),
	MINIMIZE_ATTACK("Minimize"),
	WAKE_UP_SLAP_ATTACK("Wake-up Slap"),
	COSMIC_POWER_ATTACK("Cosmic Power"),
	LUCKY_CHANT_ATTACK("Lucky Chant"),
	METRONOME_ATTACK("Metronome"),
	GRAVITY_ATTACK("Gravity"),
	MOONLIGHT_ATTACK("Moonlight"),
	STORED_POWER_ATTACK("Stored Power"),
	MIMIC_ATTACK("Mimic"),
	METEOR_MASH_ATTACK("Meteor Mash"),
	IMPRISON_ATTACK("Imprison"),
	WILL_OWISP_ATTACK("Will-o-wisp"),
	PAYBACK_ATTACK("Payback"),
	EXTRASENSORY_ATTACK("Extrasensory"),
	FIRE_BLAST_ATTACK("Fire Blast"),
	NASTY_PLOT_ATTACK("Nasty Plot"),
	ROUND_ATTACK("Round"),
	REST_ATTACK("Rest"),
	HYPER_VOICE_ATTACK("Hyper Voice"),
	LEECH_LIFE_ATTACK("Leech Life"),
	ASTONISH_ATTACK("Astonish"),
	AIR_CUTTER_ATTACK("Air Cutter"),
	MEAN_LOOK_ATTACK("Mean Look"),
	ACROBATICS_ATTACK("Acrobatics"),
	ABSORB_ATTACK("Absorb"),
	MEGA_DRAIN_ATTACK("Mega Drain"),
	NATURAL_GIFT_ATTACK("Natural Gift"),
	GIGA_DRAIN_ATTACK("Giga Drain"),
	AROMATHERAPY_ATTACK("Aromatherapy"),
	SPORE_ATTACK("Spore"),
	CROSS_POISON_ATTACK("Cross Poison"),
	XSCISSOR_ATTACK("X-scissor"),
	FORESIGHT_ATTACK("Foresight"),
	ODOR_SLEUTH_ATTACK("Odor Sleuth"),
	MIRACLE_EYE_ATTACK("Miracle Eye"),
	HOWL_ATTACK("Howl"),
	SIGNAL_BEAM_ATTACK("Signal Beam"),
	ZEN_HEADBUTT_ATTACK("Zen Headbutt"),
	PSYCHIC_ATTACK("Psychic"),
	MUD_SLAP_ATTACK("Mud-slap"),
	MAGNITUDE_ATTACK("Magnitude"),
	BULLDOZE_ATTACK("Bulldoze"),
	DIG_ATTACK("Dig"),
	EARTHQUAKE_ATTACK("Earthquake"),
	FISSURE_ATTACK("Fissure"),
	NIGHT_SLASH_ATTACK("Night Slash"),
	TRI_ATTACK_ATTACK("Tri Attack"),
	FAKE_OUT_ATTACK("Fake Out"),
	FEINT_ATTACK_ATTACK("Feint Attack"),
	TAUNT_ATTACK("Taunt"),
	PAY_DAY_ATTACK("Pay Day"),
	POWER_GEM_ATTACK("Power Gem"),
	WATER_SPORT_ATTACK("Water Sport"),
	SOAK_ATTACK("Soak"),
	PSYCH_UP_ATTACK("Psych Up"),
	AMNESIA_ATTACK("Amnesia"),
	WONDER_ROOM_ATTACK("Wonder Room"),
	AQUA_JET_ATTACK("Aqua Jet"),
	COVET_ATTACK("Covet"),
	LOW_KICK_ATTACK("Low Kick"),
	KARATE_CHOP_ATTACK("Karate Chop"),
	SEISMIC_TOSS_ATTACK("Seismic Toss"),
	SWAGGER_ATTACK("Swagger"),
	CROSS_CHOP_ATTACK("Cross Chop"),
	PUNISHMENT_ATTACK("Punishment"),
	CLOSE_COMBAT_ATTACK("Close Combat"),
	FLAME_WHEEL_ATTACK("Flame Wheel"),
	REVERSAL_ATTACK("Reversal"),
	EXTREME_SPEED_ATTACK("Extreme Speed"),
	HYPNOSIS_ATTACK("Hypnosis"),
	BUBBLE_BEAM_ATTACK("Bubble Beam"),
	MUD_SHOT_ATTACK("Mud Shot"),
	BELLY_DRUM_ATTACK("Belly Drum"),
	SUBMISSION_ATTACK("Submission"),
	DYNAMIC_PUNCH_ATTACK("Dynamic Punch"),
	MIND_READER_ATTACK("Mind Reader"),
	LOCK_ON_ATTACK("Lock-on"),
	KINESIS_ATTACK("Kinesis"),
	BARRIER_ATTACK("Barrier"),
	TELEKINESIS_ATTACK("Telekinesis"),
	INGRAIN_ATTACK("Ingrain"),
	PSYCHO_CUT_ATTACK("Psycho Cut"),
	FUTURE_SIGHT_ATTACK("Future Sight"),
	DOOM_DESIRE_ATTACK("Doom Desire"),
	CALM_MIND_ATTACK("Calm Mind"),
	LOW_SWEEP_ATTACK("Low Sweep"),
	REVENGE_ATTACK("Revenge"),
	VITAL_THROW_ATTACK("Vital Throw"),
	WRING_OUT_ATTACK("Wring Out"),
	LEAF_TORNADO_ATTACK("Leaf Tornado"),
	LEAF_STORM_ATTACK("Leaf Storm"),
	LEAF_BLADE_ATTACK("Leaf Blade"),
	CONSTRICT_ATTACK("Constrict"),
	HEX_ATTACK("Hex"),
	SLUDGE_WAVE_ATTACK("Sludge Wave"),
	MUD_SPORT_ATTACK("Mud Sport"),
	ROCK_POLISH_ATTACK("Rock Polish"),
	ROCK_THROW_ATTACK("Rock Throw"),
	ROCK_BLAST_ATTACK("Rock Blast"),
	SMACK_DOWN_ATTACK("Smack Down"),
	STEALTH_ROCK_ATTACK("Stealth Rock"),
	STONE_EDGE_ATTACK("Stone Edge"),
	STEAMROLLER_ATTACK("Steamroller"),
	HEAVY_SLAM_ATTACK("Heavy Slam"),
	STOMP_ATTACK("Stomp"),
	FLAME_CHARGE_ATTACK("Flame Charge"),
	BOUNCE_ATTACK("Bounce"),
	CURSE_ATTACK("Curse"),
	YAWN_ATTACK("Yawn"),
	HEADBUTT_ATTACK("Headbutt"),
	SLACK_OFF_ATTACK("Slack Off"),
	HEAL_PULSE_ATTACK("Heal Pulse"),
	METAL_SOUND_ATTACK("Metal Sound"),
	SPARK_ATTACK("Spark"),
	MAGNET_BOMB_ATTACK("Magnet Bomb"),
	MIRROR_SHOT_ATTACK("Mirror Shot"),
	MAGNET_RISE_ATTACK("Magnet Rise"),
	ZAP_CANNON_ATTACK("Zap Cannon"),
	BRAVE_BIRD_ATTACK("Brave Bird"),
	UPROAR_ATTACK("Uproar"),
	ACUPRESSURE_ATTACK("Acupressure"),
	DOUBLE_HIT_ATTACK("Double Hit"),
	ICY_WIND_ATTACK("Icy Wind"),
	ICE_SHARD_ATTACK("Ice Shard"),
	AQUA_RING_ATTACK("Aqua Ring"),
	AURORA_BEAM_ATTACK("Aurora Beam"),
	BRINE_ATTACK("Brine"),
	DIVE_ATTACK("Dive"),
	ICE_BEAM_ATTACK("Ice Beam"),
	SHEER_COLD_ATTACK("Sheer Cold"),
	POISON_GAS_ATTACK("Poison Gas"),
	SLUDGE_ATTACK("Sludge"),
	SLUDGE_BOMB_ATTACK("Sludge Bomb"),
	ACID_ARMOR_ATTACK("Acid Armor"),
	ICICLE_SPEAR_ATTACK("Icicle Spear"),
	CLAMP_ATTACK("Clamp"),
	RAZOR_SHELL_ATTACK("Razor Shell"),
	WHIRLPOOL_ATTACK("Whirlpool"),
	SHELL_SMASH_ATTACK("Shell Smash"),
	SPIKE_CANNON_ATTACK("Spike Cannon"),
	SPIKES_ATTACK("Spikes"),
	ICICLE_CRASH_ATTACK("Icicle Crash"),
	LICK_ATTACK("Lick"),
	SPITE_ATTACK("Spite"),
	NIGHT_SHADE_ATTACK("Night Shade"),
	SHADOW_BALL_ATTACK("Shadow Ball"),
	DREAM_EATER_ATTACK("Dream Eater"),
	DARK_PULSE_ATTACK("Dark Pulse"),
	NIGHTMARE_ATTACK("Nightmare"),
	SHADOW_PUNCH_ATTACK("Shadow Punch"),
	BIND_ATTACK("Bind"),
	ROCK_TOMB_ATTACK("Rock Tomb"),
	DRAGON_BREATH_ATTACK("Dragon Breath"),
	IRON_TAIL_ATTACK("Iron Tail"),
	MEDITATE_ATTACK("Meditate"),
	SYNCHRONOISE_ATTACK("Synchronoise"),
	PSYSHOCK_ATTACK("Psyshock"),
	VICE_GRIP_ATTACK("Vice Grip"),
	METAL_CLAW_ATTACK("Metal Claw"),
	GUILLOTINE_ATTACK("Guillotine"),
	CRABHAMMER_ATTACK("Crabhammer"),
	FLAIL_ATTACK("Flail"),
	CHARGE_ATTACK("Charge"),
	CHARGE_BEAM_ATTACK("Charge Beam"),
	MIRROR_COAT_ATTACK("Mirror Coat"),
	COUNTER_ATTACK("Counter"),
	BARRAGE_ATTACK("Barrage"),
	BULLET_SEED_ATTACK("Bullet Seed"),
	EGG_BOMB_ATTACK("Egg Bomb"),
	WOOD_HAMMER_ATTACK("Wood Hammer"),
	BONE_CLUB_ATTACK("Bone Club"),
	BONEMERANG_ATTACK("Bonemerang"),
	BONE_RUSH_ATTACK("Bone Rush"),
	ROLLING_KICK_ATTACK("Rolling Kick"),
	JUMP_KICK_ATTACK("Jump Kick"),
	BRICK_BREAK_ATTACK("Brick Break"),
	HIGH_JUMP_KICK_ATTACK("High Jump Kick"),
	BLAZE_KICK_ATTACK("Blaze Kick"),
	MEGA_KICK_ATTACK("Mega Kick"),
	COMET_PUNCH_ATTACK("Comet Punch"),
	MACH_PUNCH_ATTACK("Mach Punch"),
	BULLET_PUNCH_ATTACK("Bullet Punch"),
	VACUUM_WAVE_ATTACK("Vacuum Wave"),
	THUNDER_PUNCH_ATTACK("Thunder Punch"),
	ICE_PUNCH_ATTACK("Ice Punch"),
	FIRE_PUNCH_ATTACK("Fire Punch"),
	SKY_UPPERCUT_ATTACK("Sky Uppercut"),
	MEGA_PUNCH_ATTACK("Mega Punch"),
	FOCUS_PUNCH_ATTACK("Focus Punch"),
	ME_FIRST_ATTACK("Me First"),
	REFRESH_ATTACK("Refresh"),
	POWER_WHIP_ATTACK("Power Whip"),
	SMOG_ATTACK("Smog"),
	CLEAR_SMOG_ATTACK("Clear Smog"),
	HAMMER_ARM_ATTACK("Hammer Arm"),
	SOFT_BOILED_ATTACK("Soft-Boiled"),
	ANCIENT_POWER_ATTACK("Ancient Power"),
	TICKLE_ATTACK("Tickle"),
	DIZZY_PUNCH_ATTACK("Dizzy Punch"),
	OUTRAGE_ATTACK("Outrage"),
	DRAGON_DANCE_ATTACK("Dragon Dance"),
	DRAGON_PULSE_ATTACK("Dragon Pulse"),
	DRACO_METEOR_ATTACK("Draco Meteor"),
	WATERFALL_ATTACK("Waterfall"),
	REFLECT_TYPE_ATTACK("Reflect Type"),
	MAGICAL_LEAF_ATTACK("Magical Leaf"),
	POWER_SWAP_ATTACK("Power Swap"),
	GUARD_SWAP_ATTACK("Guard Swap"),
	COPYCAT_ATTACK("Copycat"),
	TRANSFORM_ATTACK("Transform"),
	SUBSTITUTE_ATTACK("Substitute"),
	RAZOR_WIND_ATTACK("Razor Wind"),
	LOVELY_KISS_ATTACK("Lovely Kiss"),
	POWDER_SNOW_ATTACK("Powder Snow"),
	HEART_STAMP_ATTACK("Heart Stamp"),
	FAKE_TEARS_ATTACK("Fake Tears"),
	AVALANCHE_ATTACK("Avalanche"),
	BLIZZARD_ATTACK("Blizzard"),
	SHOCK_WAVE_ATTACK("Shock Wave"),
	LAVA_PLUME_ATTACK("Lava Plume"),
	WORK_UP_ATTACK("Work Up"),
	GIGA_IMPACT_ATTACK("Giga Impact"),
	SPLASH_ATTACK("Splash"),
	MIST_ATTACK("Mist"),
	LAST_RESORT_ATTACK("Last Resort"),
	TRUMP_CARD_ATTACK("Trump Card"),
	MUDDY_WATER_ATTACK("Muddy Water"),
	CONVERSION_ATTACK("Conversion"),
	CONVERSION2_ATTACK("Conversion 2"),
	SHARPEN_ATTACK("Sharpen"),
	MAGIC_COAT_ATTACK("Magic Coat"),
	SKY_DROP_ATTACK("Sky Drop"),
	IRON_HEAD_ATTACK("Iron Head"),
	ROCK_SLIDE_ATTACK("Rock Slide"),
	SNORE_ATTACK("Snore"),
	SLEEP_TALK_ATTACK("Sleep Talk"),
	BLOCK_ATTACK("Block"),
	SKY_ATTACK_ATTACK("Sky Attack"),
	DRAGON_RUSH_ATTACK("Dragon Rush"),
	AURA_SPHERE_ATTACK("Aura Sphere"),
	PSYSTRIKE_ATTACK("Psystrike"),
	ERUPTION_ATTACK("Eruption"),
	CHARM_ATTACK("Charm"),
	ECHOED_VOICE_ATTACK("Echoed Voice"),
	PSYCHO_SHIFT_ATTACK("Psycho Shift"),
	SHADOW_SNEAK_ATTACK("Shadow Sneak"),
	SPIDER_WEB_ATTACK("Spider Web"),
	SWEET_KISS_ATTACK("Sweet Kiss"),
	OMINOUS_WIND_ATTACK("Ominous Wind"),
	COTTON_SPORE_ATTACK("Cotton Spore"),
	COTTON_GUARD_ATTACK("Cotton Guard"),
	GRASS_WHISTLE_ATTACK("Grass Whistle"),
	TORMENT_ATTACK("Torment"),
	HIDDEN_POWER_ATTACK("Hidden Power"),
	PSYWAVE_ATTACK("Psywave"),
	PAIN_SPLIT_ATTACK("Pain Split"),
	BIDE_ATTACK("Bide"),
	AUTOTOMIZE_ATTACK("Autotomize"),
	STRUGGLE_BUG_ATTACK("Struggle Bug"),
	POWER_TRICK_ATTACK("Power Trick"),
	POWER_SPLIT_ATTACK("Power Split"),
	GUARD_SPLIT_ATTACK("Guard Split"),
	HONE_CLAWS_ATTACK("Hone Claws"),
	BEAT_UP_ATTACK("Beat Up"),
	OCTAZOOKA_ATTACK("Octazooka"),
	PRESENT_ATTACK("Present"),
	STEEL_WING_ATTACK("Steel Wing"),
	SKETCH_ATTACK("Sketch"),
	TRIPLE_KICK_ATTACK("Triple Kick"),
	MILK_DRINK_ATTACK("Milk Drink"),
	HEAL_BELL_ATTACK("Heal Bell"),
	WEATHER_BALL_ATTACK("Weather Ball"),
	AEROBLAST_ATTACK("Aeroblast"),
	SACRED_FIRE_ATTACK("Sacred Fire"),
	HEAL_BLOCK_ATTACK("Heal Block"),
	ENERGY_BALL_ATTACK("Energy Ball"),
	BULK_UP_ATTACK("Bulk Up"),
	THIEF_ATTACK("Thief"),
	ATTRACT_ATTACK("Attract"),
	FORCE_PALM_ATTACK("Force Palm"),
	ARM_THRUST_ATTACK("Arm Thrust"),
	SMELLING_SALTS_ATTACK("Smelling Salts"),
	ASSIST_ATTACK("Assist"),
	METAL_BURST_ATTACK("Metal Burst"),
	WILD_CHARGE_ATTACK("Wild Charge"),
	FLASH_ATTACK("Flash"),
	TAIL_GLOW_ATTACK("Tail Glow"),
	WATER_SPOUT_ATTACK("Water Spout"),
	TEETER_DANCE_ATTACK("Teeter Dance"),
	NEEDLE_ARM_ATTACK("Needle Arm"),
	VENOSHOCK_ATTACK("Venoshock"),
	SNATCH_ATTACK("Snatch"),
	ICE_BALL_ATTACK("Ice Ball"),
	HEAD_SMASH_ATTACK("Head Smash"),
	MIST_BALL_ATTACK("Mist Ball"),
	LUSTER_PURGE_ATTACK("Luster Purge"),
	PSYCHO_BOOST_ATTACK("Psycho Boost"),
	FACADE_ATTACK("Facade"),
	DEFEND_ORDER_ATTACK("Defend Order"),
	HEAL_ORDER_ATTACK("Heal Order"),
	ATTACK_ORDER_ATTACK("Attack Order"),
	CHATTER_ATTACK("Chatter"),
	DUAL_CHOP_ATTACK("Dual Chop"),
	ROCK_WRECKER_ATTACK("Rock Wrecker"),
	TRICK_ROOM_ATTACK("Trick Room"),
	ROAR_OF_TIME_ATTACK("Roar Of Time"),
	SPACIAL_REND_ATTACK("Spacial Rend"),
	MAGMA_STORM_ATTACK("Magma Storm"),
	CRUSH_GRIP_ATTACK("Crush Grip"),
	SHADOW_FORCE_ATTACK("Shadow Force"),
	HEART_SWAP_ATTACK("Heart Swap"),
	DARK_VOID_ATTACK("Dark Void"),
	SEED_FLARE_ATTACK("Seed Flare"),
	JUDGMENT_ATTACK("Judgment"),
	SEARING_SHOT_ATTACK("Searing Shot"),
	INCINERATE_ATTACK("Incinerate"),
	OVERHEAT_ATTACK("Overheat"),
	HEAT_CRASH_ATTACK("Heat Crash"),
	GRASS_KNOT_ATTACK("Grass Knot"),
	SCALD_ATTACK("Scald"),
	DRAIN_PUNCH_ATTACK("Drain Punch"),
	STORM_THROW_ATTACK("Storm Throw"),
	FROST_BREATH_ATTACK("Frost Breath"),
	ROCK_SMASH_ATTACK("Rock Smash"),
	ROCK_CLIMB_ATTACK("Rock Climb"),
	NIGHT_DAZE_ATTACK("Night Daze"),
	TAIL_SLAP_ATTACK("Tail Slap"),
	DEFOG_ATTACK("Defog"),
	HORN_LEECH_ATTACK("Horn Leech"),
	ELECTROWEB_ATTACK("Electroweb"),
	GEAR_GRIND_ATTACK("Gear Grind"),
	SHIFT_GEAR_ATTACK("Shift Gear"),
	HEAD_CHARGE_ATTACK("Head Charge"),
	FIERY_DANCE_ATTACK("Fiery Dance"),
	SACRED_SWORD_ATTACK("Sacred Sword"),
	SECRET_SWORD_ATTACK("Secret Sword"),
	FUSION_FLARE_ATTACK("Fusion Flare"),
	FUSION_BOLT_ATTACK("Fusion Bolt"),
	BLUE_FLARE_ATTACK("Blue Flare"),
	BOLT_STRIKE_ATTACK("Bolt Strike"),
	GLACIATE_ATTACK("Glaciate"),
	TECHNO_BLAST_ATTACK("Techno Blast"),
	EXPLOSION_ATTACK("Explosion"),
	SELF_DESTRUCT_ATTACK("Self-Destruct"),
	FLING_ATTACK("Fling"),
	FREEZE_SHOCK_ATTACK("Freeze Shock"),
	SECRET_POWER_ATTACK("Secret Power"),
	FINAL_GAMBIT_ATTACK("Final Gambit"),
	GASTRO_ACID_ATTACK("Gastro Acid"),
	HEALING_WISH_ATTACK("Healing Wish"),
	LUNAR_DANCE_ATTACK("Lunar Dance"),
	ROAR_ATTACK("Roar"),
	GRUDGE_ATTACK("Grudge"),
	RETALIATE_ATTACK("Retaliate"),
	CIRCLE_THROW_ATTACK("Circle Throw"),
	TELEPORT_ATTACK("Teleport"),
	ROLE_PLAY_ATTACK("Role Play"),
	KNOCK_OFF_ATTACK("Knock Off"),
	WHIRLWIND_ATTACK("Whirlwind"),
	BESTOW_ATTACK("Bestow"),
	SWITCHEROO_ATTACK("Switcheroo"),
	TRICK_ATTACK("Trick"),
	MEMENTO_ATTACK("Memento"),
	DESTINY_BOND_ATTACK("Destiny Bond"),
	CAMOUFLAGE_ATTACK("Camouflage"),
	RECYCLE_ATTACK("Recycle"),
	UTURN_ATTACK("U-turn"),
	BATON_PASS_ATTACK("Baton Pass"),
	PERISH_SONG_ATTACK("Perish Song"),
	DRAGON_TAIL_ATTACK("Dragon Tail"),
	FOUL_PLAY_ATTACK("Foul Play"),
	EMBARGO_ATTACK("Embargo"),
	NATURE_POWER_ATTACK("Nature Power"),
	ENTRAINMENT_ATTACK("Entrainment"),
	MAGIC_ROOM_ATTACK("Magic Room"),
	SIMPLE_BEAM_ATTACK("Simple Beam"),
	SKILL_SWAP_ATTACK("Skill Swap"),
	VOLT_SWITCH_ATTACK("Volt Switch"),
	RELIC_SONG_ATTACK("Relic Song"),
	SNARL_ATTACK("Snarl"),
	ICE_BURN_ATTACK("Ice Burn"),
	VCREATE_ATTACK("V-create"),
	SURF_ATTACK("Surf"),
	VOLT_TACKLE_ATTACK("Volt Tackle"),
	FOCUS_BLAST_ATTACK("Focus Blast"),
	LEECH_SEED_EFFECT("LeechSeed"),
	BAD_POISON_EFFECT("BadPoison"),
	FLINCH_EFFECT("Flinch"),
	FIRE_SPIN_EFFECT("FireSpin"),
	MAGMA_STORM_EFFECT("MagmaStorm"),
	CLAMPED_EFFECT("Clamped"),
	WHIRLPOOL_EFFECT("Whirlpool"),
	WRAPPED_EFFECT("Wrapped"),
	BINDED_EFFECT("Binded"),
	SAND_TOMB_EFFECT("SandTomb"),
	PROTECTING_EFFECT("Protecting"),
	QUICK_GUARD_EFFECT("QuickGuard"),
	BRACING_EFFECT("Bracing"),
	CONFUSION_EFFECT("Confusion"),
	SELF_CONFUSION_EFFECT("SelfConfusion"),
	SAFEGUARD_EFFECT("Safeguard"),
	GUARD_SPECIAL_EFFECT("GuardSpecial"),
	ENCORE_EFFECT("Encore"),
	DISABLE_EFFECT("Disable"),
	RAISE_CRITS_EFFECT("RaiseCrits"),
	CHANGE_ITEM_EFFECT("ChangeItem"),
	CHANGE_TYPE_EFFECT("ChangeType"),
	CHANGE_ABILITY_EFFECT("ChangeAbility"),
	STOCKPILE_EFFECT("Stockpile"),
	USED_DEFENSE_CURL_EFFECT("UsedDefenseCurl"),
	USED_MINIMIZE_EFFECT("UsedMinimize"),
	MIMIC_EFFECT("Mimic"),
	IMPRISON_EFFECT("Imprison"),
	TRAPPED_EFFECT("Trapped"),
	FORESIGHT_EFFECT("Foresight"),
	MIRACLE_EYE_EFFECT("MiracleEye"),
	TORMENT_EFFECT("Torment"),
	TAUNT_EFFECT("Taunt"),
	LOCK_ON_EFFECT("LockOn"),
	TELEKINESIS_EFFECT("Telekinesis"),
	INGRAIN_EFFECT("Ingrain"),
	GROUNDED_EFFECT("Grounded"),
	CURSE_EFFECT("Curse"),
	YAWN_EFFECT("Yawn"),
	MAGNET_RISE_EFFECT("MagnetRise"),
	UPROAR_EFFECT("Uproar"),
	AQUA_RING_EFFECT("AquaRing"),
	NIGHTMARE_EFFECT("Nightmare"),
	CHARGE_EFFECT("Charge"),
	FOCUSING_EFFECT("Focusing"),
	FIDDY_PERCENT_STRONGER_EFFECT("FiddyPercentStronger"),
	TRANSFORMED_EFFECT("Transformed"),
	SUBSTITUTE_EFFECT("Substitute"),
	MIST_EFFECT("Mist"),
	MAGIC_COAT_EFFECT("MagicCoat"),
	BIDE_EFFECT("Bide"),
	HALF_WEIGHT_EFFECT("HalfWeight"),
	POWER_TRICK_EFFECT("PowerTrick"),
	POWER_SPLIT_EFFECT("PowerSplit"),
	GUARD_SPLIT_EFFECT("GuardSplit"),
	HEAL_BLOCK_EFFECT("HealBlock"),
	INFATUATED_EFFECT("Infatuated"),
	SNATCH_EFFECT("Snatch"),
	GRUDGE_EFFECT("Grudge"),
	DESTINY_BOND_EFFECT("DestinyBond"),
	PERISH_SONG_EFFECT("PerishSong"),
	EMBARGO_EFFECT("Embargo"),
	CONSUMED_ITEM_EFFECT("ConsumedItem"),
	REFLECT_EFFECT("Reflect"),
	LIGHT_SCREEN_EFFECT("LightScreen"),
	TAILWIND_EFFECT("Tailwind"),
	STEALTH_ROCK_EFFECT("StealthRock"),
	TOXIC_SPIKES_EFFECT("ToxicSpikes"),
	SPIKES_EFFECT("Spikes"),
	WISH_EFFECT("Wish"),
	LUCKY_CHANT_EFFECT("LuckyChant"),
	FUTURE_SIGHT_EFFECT("FutureSight"),
	DOOM_DESIRE_EFFECT("DoomDesire"),
	HEAL_SWITCH_EFFECT("HealSwitch"),
	DEAD_ALLY_EFFECT("DeadAlly"),
	PAY_DAY_EFFECT("PayDay"),
	DOUBLE_MONEY_EFFECT("DoubleMoney"),
	GRAVITY_EFFECT("Gravity"),
	WATER_SPORT_EFFECT("WaterSport"),
	MUD_SPORT_EFFECT("MudSport"),
	WONDER_ROOM_EFFECT("WonderRoom"),
	TRICK_ROOM_EFFECT("TrickRoom"),
	MAGIC_ROOM_EFFECT("MagicRoom"),
	CLEAR_SKIES_EFFECT("ClearSkies"),
	RAINING_EFFECT("Raining"),
	SUNNY_EFFECT("Sunny"),
	SANDSTORM_EFFECT("Sandstorm"),
	HAILING_EFFECT("Hailing"),
	NONE_ABILITY("None"),
	OVERGROW_ABILITY("Overgrow"),
	CHLOROPHYLL_ABILITY("Chlorophyll"),
	BLAZE_ABILITY("Blaze"),
	SOLAR_POWER_ABILITY("Solar Power"),
	TORRENT_ABILITY("Torrent"),
	RAIN_DISH_ABILITY("Rain Dish"),
	SHIELD_DUST_ABILITY("Shield Dust"),
	SHED_SKIN_ABILITY("Shed Skin"),
	COMPOUNDEYES_ABILITY("Compoundeyes"),
	TINTED_LENS_ABILITY("Tinted Lens"),
	SWARM_ABILITY("Swarm"),
	SNIPER_ABILITY("Sniper"),
	KEEN_EYE_ABILITY("Keen Eye"),
	TANGLED_FEET_ABILITY("Tangled Feet"),
	GUTS_ABILITY("Guts"),
	INTIMIDATE_ABILITY("Intimidate"),
	STATIC_ABILITY("Static"),
	LIGHTNINGROD_ABILITY("Lightningrod"),
	SAND_VEIL_ABILITY("Sand Veil"),
	SAND_RUSH_ABILITY("Sand Rush"),
	POISON_POINT_ABILITY("Poison Point"),
	RIVALRY_ABILITY("Rivalry"),
	CUTE_CHARM_ABILITY("Cute Charm"),
	MAGIC_GUARD_ABILITY("Magic Guard"),
	FLASH_FIRE_ABILITY("Flash Fire"),
	DROUGHT_ABILITY("Drought"),
	FRISK_ABILITY("Frisk"),
	INNER_FOCUS_ABILITY("Inner Focus"),
	INFILTRATOR_ABILITY("Infiltrator"),
	STENCH_ABILITY("Stench"),
	EFFECT_SPORE_ABILITY("Effect Spore"),
	DRY_SKIN_ABILITY("Dry Skin"),
	ARENA_TRAP_ABILITY("Arena Trap"),
	TECHNICIAN_ABILITY("Technician"),
	LIMBER_ABILITY("Limber"),
	DAMP_ABILITY("Damp"),
	CLOUD_NINE_ABILITY("Cloud Nine"),
	VITAL_SPIRIT_ABILITY("Vital Spirit"),
	INSOMNIA_ABILITY("Insomnia"),
	ANGER_POINT_ABILITY("Anger Point"),
	SYNCHRONIZE_ABILITY("Synchronize"),
	NO_GUARD_ABILITY("No Guard"),
	OWN_TEMPO_ABILITY("Own Tempo"),
	CLEAR_BODY_ABILITY("Clear Body"),
	LIQUID_OOZE_ABILITY("Liquid Ooze"),
	ROCK_HEAD_ABILITY("Rock Head"),
	STURDY_ABILITY("Sturdy"),
	OBLIVIOUS_ABILITY("Oblivious"),
	MAGNET_PULL_ABILITY("Magnet Pull"),
	UNAWARE_ABILITY("Unaware"),
	SIMPLE_ABILITY("Simple"),
	EARLY_BIRD_ABILITY("Early Bird"),
	THICK_FAT_ABILITY("Thick Fat"),
	HYDRATION_ABILITY("Hydration"),
	SHELL_ARMOR_ABILITY("Shell Armor"),
	BATTLE_ARMOR_ABILITY("Battle Armor"),
	SKILL_LINK_ABILITY("Skill Link"),
	LEVITATE_ABILITY("Levitate"),
	FOREWARN_ABILITY("Forewarn"),
	HYPER_CUTTER_ABILITY("Hyper Cutter"),
	SOUNDPROOF_ABILITY("Soundproof"),
	RECKLESS_ABILITY("Reckless"),
	IRON_FIST_ABILITY("Iron Fist"),
	NATURAL_CURE_ABILITY("Natural Cure"),
	SERENE_GRACE_ABILITY("Serene Grace"),
	LEAF_GUARD_ABILITY("Leaf Guard"),
	SCRAPPY_ABILITY("Scrappy"),
	SWIFT_SWIM_ABILITY("Swift Swim"),
	WATER_VEIL_ABILITY("Water Veil"),
	FILTER_ABILITY("Filter"),
	FLAME_BODY_ABILITY("Flame Body"),
	RATTLED_ABILITY("Rattled"),
	MOXIE_ABILITY("Moxie"),
	IMPOSTER_ABILITY("Imposter"),
	ADAPTABILITY_ABILITY("Adaptability"),
	WATER_ABSORB_ABILITY("Water Absorb"),
	VOLT_ABSORB_ABILITY("Volt Absorb"),
	QUICK_FEET_ABILITY("Quick Feet"),
	TRACE_ABILITY("Trace"),
	DOWNLOAD_ABILITY("Download"),
	PRESSURE_ABILITY("Pressure"),
	IMMUNITY_ABILITY("Immunity"),
	SNOW_CLOAK_ABILITY("Snow Cloak"),
	MARVEL_SCALE_ABILITY("Marvel Scale"),
	MULTISCALE_ABILITY("Multiscale"),
	SHEER_FORCE_ABILITY("Sheer Force"),
	HUSTLE_ABILITY("Hustle"),
	HUGE_POWER_ABILITY("Huge Power"),
	SPEED_BOOST_ABILITY("Speed Boost"),
	MAGIC_BOUNCE_ABILITY("Magic Bounce"),
	SUPER_LUCK_ABILITY("Super Luck"),
	SHADOW_TAG_ABILITY("Shadow Tag"),
	OVERCOAT_ABILITY("Overcoat"),
	MAGMA_ARMOR_ABILITY("Magma Armor"),
	SUCTION_CUPS_ABILITY("Suction Cups"),
	STEADFAST_ABILITY("Steadfast"),
	SAND_STREAM_ABILITY("Sand Stream"),
	REGENERATOR_ABILITY("Regenerator"),
	POISON_HEAL_ABILITY("Poison Heal"),
	TRUANT_ABILITY("Truant"),
	WONDER_GUARD_ABILITY("Wonder Guard"),
	NORMALIZE_ABILITY("Normalize"),
	STALL_ABILITY("Stall"),
	PURE_POWER_ABILITY("Pure Power"),
	ROUGH_SKIN_ABILITY("Rough Skin"),
	SOLID_ROCK_ABILITY("Solid Rock"),
	WHITE_SMOKE_ABILITY("White Smoke"),
	TOXIC_BOOST_ABILITY("Toxic Boost"),
	ANTICIPATION_ABILITY("Anticipation"),
	STORM_DRAIN_ABILITY("Storm Drain"),
	COLOR_CHANGE_ABILITY("Color Change"),
	ICE_BODY_ABILITY("Ice Body"),
	LIGHT_METAL_ABILITY("Light Metal"),
	DRIZZLE_ABILITY("Drizzle"),
	AIR_LOCK_ABILITY("Air Lock"),
	DEFIANT_ABILITY("Defiant"),
	FLOWER_GIFT_ABILITY("Flower Gift"),
	AFTERMATH_ABILITY("Aftermath"),
	HEATPROOF_ABILITY("Heatproof"),
	SAND_FORCE_ABILITY("Sand Force"),
	SNOW_WARNING_ABILITY("Snow Warning"),
	MOTOR_DRIVE_ABILITY("Motor Drive"),
	JUSTIFIED_ABILITY("Justified"),
	CURSED_BODY_ABILITY("Cursed Body"),
	SLOW_START_ABILITY("Slow Start"),
	BAD_DREAMS_ABILITY("Bad Dreams"),
	VICTORY_STAR_ABILITY("Victory Star"),
	CONTRARY_ABILITY("Contrary"),
	BIG_PECKS_ABILITY("Big Pecks"),
	POISON_TOUCH_ABILITY("Poison Touch"),
	PRANKSTER_ABILITY("Prankster"),
	WONDER_SKIN_ABILITY("Wonder Skin"),
	MUMMY_ABILITY("Mummy"),
	DEFEATIST_ABILITY("Defeatist"),
	WEAK_ARMOR_ABILITY("Weak Armor"),
	ILLUSION_ABILITY("Illusion"),
	ANALYTIC_ABILITY("Analytic"),
	SAP_SIPPER_ABILITY("Sap Sipper"),
	IRON_BARBS_ABILITY("Iron Barbs"),
	MOLD_BREAKER_ABILITY("Mold Breaker"),
	TERAVOLT_ABILITY("Teravolt"),
	TURBOBLAZE_ABILITY("Turboblaze"),
	RUN_AWAY_ABILITY("Run Away"),
	STICKY_HOLD_ABILITY("Sticky Hold"),
	KLUTZ_ABILITY("Klutz"),
	UNBURDEN_ABILITY("Unburden"),
	PICKPOCKET_ABILITY("Pickpocket"),
	HARVEST_ABILITY("Harvest"),
	PICKUP_ABILITY("Pickup"),
	UNNERVE_ABILITY("Unnerve"),
	HONEY_GATHER_ABILITY("Honey Gather"),
	GLUTTONY_ABILITY("Gluttony"),
	MULTITYPE_ABILITY("Multitype"),
	FORECAST_ABILITY("Forecast"),
	NONE_ITEM("None"),
	SYRUP_ITEM("Syrup"),
	BICYCLE_ITEM("Bicycle"),
	SURFBOARD_ITEM("Surfboard"),
	FISHING_ROD_ITEM("Fishing Rod"),
	ABSORB_BULB_ITEM("Absorb Bulb"),
	AIR_BALLOON_ITEM("Air Balloon"),
	AMULET_COIN_ITEM("Amulet Coin"),
	BIG_ROOT_ITEM("Big Root"),
	BINDING_BAND_ITEM("Binding Band"),
	BLACK_SLUDGE_ITEM("Black Sludge"),
	BRIGHT_POWDER_ITEM("Bright Powder"),
	CELL_BATTERY_ITEM("Cell Battery"),
	CHOICE_BAND_ITEM("Choice Band"),
	CHOICE_SCARF_ITEM("Choice Scarf"),
	CHOICE_SPECS_ITEM("Choice Specs"),
	CLEANSE_TAG_ITEM("Cleanse Tag"),
	DAMP_ROCK_ITEM("Damp Rock"),
	HEAT_ROCK_ITEM("Heat Rock"),
	ICY_ROCK_ITEM("Icy Rock"),
	SMOOTH_ROCK_ITEM("Smooth Rock"),
	EJECT_BUTTON_ITEM("Eject Button"),
	DESTINY_KNOT_ITEM("Destiny Knot"),
	EXPERT_BELT_ITEM("Expert Belt"),
	FLAME_ORB_ITEM("Flame Orb"),
	TOXIC_ORB_ITEM("Toxic Orb"),
	FLOAT_STONE_ITEM("Float Stone"),
	FOCUS_BAND_ITEM("Focus Band"),
	FOCUS_SASH_ITEM("Focus Sash"),
	GRIP_CLAW_ITEM("Grip Claw"),
	GRISEOUS_ORB_ITEM("Griseous Orb"),
	IRON_BALL_ITEM("Iron Ball"),
	LAGGING_TAIL_ITEM("Lagging Tail"),
	LIFE_ORB_ITEM("Life Orb"),
	LIGHT_BALL_ITEM("Light Ball"),
	LIGHT_CLAY_ITEM("Light Clay"),
	LUCKY_EGG_ITEM("Lucky Egg"),
	LUCKY_PUNCH_ITEM("Lucky Punch"),
	MACHO_BRACE_ITEM("Macho Brace"),
	MENTAL_HERB_ITEM("Mental Herb"),
	METAL_POWDER_ITEM("Metal Powder"),
	METRONOME_ITEM("Metronome"),
	MUSCLE_BAND_ITEM("Muscle Band"),
	POWER_ANKLET_ITEM("Power Anklet"),
	POWER_BAND_ITEM("Power Band"),
	POWER_BELT_ITEM("Power Belt"),
	POWER_BRACER_ITEM("Power Bracer"),
	POWER_LENS_ITEM("Power Lens"),
	POWER_WEIGHT_ITEM("Power Weight"),
	QUICK_CLAW_ITEM("Quick Claw"),
	QUICK_POWDER_ITEM("Quick Powder"),
	RED_CARD_ITEM("Red Card"),
	RING_TARGET_ITEM("Ring Target"),
	ROCKY_HELMET_ITEM("Rocky Helmet"),
	SAFETY_GOGGLES_ITEM("Safety Goggles"),
	SCOPE_LENS_ITEM("Scope Lens"),
	SHED_SHELL_ITEM("Shed Shell"),
	SHELL_BELL_ITEM("Shell Bell"),
	SMOKE_BALL_ITEM("Smoke Ball"),
	SNOWBALL_ITEM("Snowball"),
	SOUL_DEW_ITEM("Soul Dew"),
	STICK_ITEM("Stick"),
	STICKY_BARB_ITEM("Sticky Barb"),
	THICK_CLUB_ITEM("Thick Club"),
	WEAKNESS_POLICY_ITEM("Weakness Policy"),
	WHITE_HERB_ITEM("White Herb"),
	WIDE_LENS_ITEM("Wide Lens"),
	WISE_GLASSES_ITEM("Wise Glasses"),
	ZOOM_LENS_ITEM("Zoom Lens"),
	FULL_INCENSE_ITEM("Full Incense"),
	LAX_INCENSE_ITEM("Lax Incense"),
	LUCK_INCENSE_ITEM("Luck Incense"),
	ODD_INCENSE_ITEM("Odd Incense"),
	PURE_INCENSE_ITEM("Pure Incense"),
	ROCK_INCENSE_ITEM("Rock Incense"),
	ROSE_INCENSE_ITEM("Rose Incense"),
	SEA_INCENSE_ITEM("Sea Incense"),
	WAVE_INCENSE_ITEM("Wave Incense"),
	DRACO_PLATE_ITEM("Draco Plate"),
	DREAD_PLATE_ITEM("Dread Plate"),
	EARTH_PLATE_ITEM("Earth Plate"),
	FIST_PLATE_ITEM("Fist Plate"),
	FLAME_PLATE_ITEM("Flame Plate"),
	ICICLE_PLATE_ITEM("Icicle Plate"),
	INSECT_PLATE_ITEM("Insect Plate"),
	IRON_PLATE_ITEM("Iron Plate"),
	MEADOW_PLATE_ITEM("Meadow Plate"),
	MIND_PLATE_ITEM("Mind Plate"),
	SKY_PLATE_ITEM("Sky Plate"),
	SPLASH_PLATE_ITEM("Splash Plate"),
	SPOOKY_PLATE_ITEM("Spooky Plate"),
	STONE_PLATE_ITEM("Stone Plate"),
	TOXIC_PLATE_ITEM("Toxic Plate"),
	ZAP_PLATE_ITEM("Zap Plate"),
	BURN_DRIVE_ITEM("Burn Drive"),
	CHILL_DRIVE_ITEM("Chill Drive"),
	DOUSE_DRIVE_ITEM("Douse Drive"),
	SHOCK_DRIVE_ITEM("Shock Drive"),
	FIRE_GEM_ITEM("Fire Gem"),
	WATER_GEM_ITEM("Water Gem"),
	ELECTRIC_GEM_ITEM("Electric Gem"),
	GRASS_GEM_ITEM("Grass Gem"),
	ICE_GEM_ITEM("Ice Gem"),
	FIGHTING_GEM_ITEM("Fighting Gem"),
	POISON_GEM_ITEM("Poison Gem"),
	GROUND_GEM_ITEM("Ground Gem"),
	FLYING_GEM_ITEM("Flying Gem"),
	PSYCHIC_GEM_ITEM("Psychic Gem"),
	BUG_GEM_ITEM("Bug Gem"),
	ROCK_GEM_ITEM("Rock Gem"),
	GHOST_GEM_ITEM("Ghost Gem"),
	DRAGON_GEM_ITEM("Dragon Gem"),
	DARK_GEM_ITEM("Dark Gem"),
	STEEL_GEM_ITEM("Steel Gem"),
	NORMAL_GEM_ITEM("Normal Gem"),
	LEFTOVERS_ITEM("Leftovers"),
	BLACK_BELT_ITEM("Black Belt"),
	BLACK_GLASSES_ITEM("Black Glasses"),
	CHARCOAL_ITEM("Charcoal"),
	DRAGON_FANG_ITEM("Dragon Fang"),
	HARD_STONE_ITEM("Hard Stone"),
	MAGNET_ITEM("Magnet"),
	METAL_COAT_ITEM("Metal Coat"),
	MIRACLE_SEED_ITEM("Miracle Seed"),
	MYSTIC_WATER_ITEM("Mystic Water"),
	NEVER_MELT_ICE_ITEM("NeverMeltIce"),
	POISON_BARB_ITEM("Poison Barb"),
	SHARP_BEAK_ITEM("Sharp Beak"),
	SILK_SCARF_ITEM("Silk Scarf"),
	SILVER_POWDER_ITEM("Silver Powder"),
	SOFT_SAND_ITEM("Soft Sand"),
	SPELL_TAG_ITEM("Spell Tag"),
	TWISTED_SPOON_ITEM("Twisted Spoon"),
	DAWN_STONE_ITEM("Dawn Stone"),
	DEEP_SEA_SCALE_ITEM("DeepSeaScale"),
	DEEP_SEA_TOOTH_ITEM("DeepSeaTooth"),
	DRAGON_SCALE_ITEM("Dragon Scale"),
	DUBIOUS_DISC_ITEM("Dubious Disc"),
	DUSK_STONE_ITEM("Dusk Stone"),
	ELECTIRIZER_ITEM("Electirizer"),
	FIRE_STONE_ITEM("Fire Stone"),
	KINGS_ROCK_ITEM("King's Rock"),
	LEAF_STONE_ITEM("Leaf Stone"),
	MAGMARIZER_ITEM("Magmarizer"),
	MOON_STONE_ITEM("Moon Stone"),
	OVAL_STONE_ITEM("Oval Stone"),
	EVERSTONE_ITEM("Everstone"),
	PRISM_SCALE_ITEM("Prism Scale"),
	PROTECTOR_ITEM("Protector"),
	RAZOR_CLAW_ITEM("Razor Claw"),
	RAZOR_FANG_ITEM("Razor Fang"),
	REAPER_CLOTH_ITEM("Reaper Cloth"),
	SHINY_STONE_ITEM("Shiny Stone"),
	SUN_STONE_ITEM("Sun Stone"),
	THUNDER_STONE_ITEM("Thunder Stone"),
	UP_GRADE_ITEM("Up-Grade"),
	WATER_STONE_ITEM("Water Stone"),
	ANTIDOTE_ITEM("Antidote"),
	AWAKENING_ITEM("Awakening"),
	BURN_HEAL_ITEM("Burn Heal"),
	ICE_HEAL_ITEM("Ice Heal"),
	PARALYZE_HEAL_ITEM("Paralyze Heal"),
	FULL_HEAL_ITEM("Full Heal"),
	FULL_RESTORE_ITEM("Full Restore"),
	ELIXIR_ITEM("Elixir"),
	MAX_ELIXIR_ITEM("Max Elixir"),
	ETHER_ITEM("Ether"),
	MAX_ETHER_ITEM("Max Ether"),
	BERRY_JUICE_ITEM("Berry Juice"),
	SWEET_HEART_ITEM("Sweet Heart"),
	POTION_ITEM("Potion"),
	ENERGY_POWDER_ITEM("Energy Powder"),
	FRESH_WATER_ITEM("Fresh Water"),
	SUPER_POTION_ITEM("Super Potion"),
	SODA_POP_ITEM("Soda Pop"),
	LEMONADE_ITEM("Lemonade"),
	MOOMOO_MILK_ITEM("Moomoo Milk"),
	ENERGY_ROOT_ITEM("Energy Root"),
	HYPER_POTION_ITEM("Hyper Potion"),
	MAX_POTION_ITEM("Max Potion"),
	REVIVE_ITEM("Revive"),
	MAX_REVIVE_ITEM("Max Revive"),
	REVIVAL_HERB_ITEM("Revival Herb"),
	SACRED_ASH_ITEM("Sacred Ash"),
	DIRE_HIT_ITEM("Dire Hit"),
	GUARD_SPEC_ITEM("Guard Spec."),
	XACCURACY_ITEM("X Accuracy"),
	XATTACK_ITEM("X Attack"),
	XDEFEND_ITEM("X Defend"),
	XSP_DEF_ITEM("X Sp. Def"),
	XSPECIAL_ITEM("X Special"),
	XSPEED_ITEM("X Speed"),
	CALCIUM_ITEM("Calcium"),
	CARBOS_ITEM("Carbos"),
	CLEVER_WING_ITEM("Clever Wing"),
	HEALTH_WING_ITEM("Health Wing"),
	HPUP_ITEM("HP Up"),
	GENIUS_WING_ITEM("Genius Wing"),
	IRON_ITEM("Iron"),
	MUSCLE_WING_ITEM("Muscle Wing"),
	PPMAX_ITEM("PP Max"),
	PPUP_ITEM("PP Up"),
	PROTEIN_ITEM("Protein"),
	RARE_CANDY_ITEM("Rare Candy"),
	RESIST_WING_ITEM("Resist Wing"),
	SWIFT_WING_ITEM("Swift Wing"),
	ZINC_ITEM("Zinc"),
	CHERISH_BALL_ITEM("Cherish Ball"),
	DIVE_BALL_ITEM("Dive Ball"),
	DUSK_BALL_ITEM("Dusk Ball"),
	FAST_BALL_ITEM("Fast Ball"),
	GREAT_BALL_ITEM("Great Ball"),
	HEAL_BALL_ITEM("Heal Ball"),
	HEAVY_BALL_ITEM("Heavy Ball"),
	LEVEL_BALL_ITEM("Level Ball"),
	LOVE_BALL_ITEM("Love Ball"),
	LURE_BALL_ITEM("Lure Ball"),
	LUXURY_BALL_ITEM("Luxury Ball"),
	MASTER_BALL_ITEM("Master Ball"),
	MOON_BALL_ITEM("Moon Ball"),
	NEST_BALL_ITEM("Nest Ball"),
	NET_BALL_ITEM("Net Ball"),
	POKE_BALL_ITEM("Pok\u00e9 Ball"),
	PREMIER_BALL_ITEM("Premier Ball"),
	QUICK_BALL_ITEM("Quick Ball"),
	REPEAT_BALL_ITEM("Repeat Ball"),
	SAFARI_BALL_ITEM("Safari Ball"),
	TIMER_BALL_ITEM("Timer Ball"),
	ULTRA_BALL_ITEM("Ultra Ball"),
	CHERI_BERRY_ITEM("Cheri Berry"),
	CHESTO_BERRY_ITEM("Chesto Berry"),
	PECHA_BERRY_ITEM("Pecha Berry"),
	RAWST_BERRY_ITEM("Rawst Berry"),
	ASPEAR_BERRY_ITEM("Aspear Berry"),
	LEPPA_BERRY_ITEM("Leppa Berry"),
	ORAN_BERRY_ITEM("Oran Berry"),
	PERSIM_BERRY_ITEM("Persim Berry"),
	LUM_BERRY_ITEM("Lum Berry"),
	SITRUS_BERRY_ITEM("Sitrus Berry"),
	RAZZ_BERRY_ITEM("Razz Berry"),
	POMEG_BERRY_ITEM("Pomeg Berry"),
	KELPSY_BERRY_ITEM("Kelpsy Berry"),
	QUALOT_BERRY_ITEM("Qualot Berry"),
	HONDEW_BERRY_ITEM("Hondew Berry"),
	GREPA_BERRY_ITEM("Grepa Berry"),
	TAMATO_BERRY_ITEM("Tamato Berry"),
	OCCA_BERRY_ITEM("Occa Berry"),
	PASSHO_BERRY_ITEM("Passho Berry"),
	WACAN_BERRY_ITEM("Wacan Berry"),
	RINDO_BERRY_ITEM("Rindo Berry"),
	YACHE_BERRY_ITEM("Yache Berry"),
	CHOPLE_BERRY_ITEM("Chople Berry"),
	KEBIA_BERRY_ITEM("Kebia Berry"),
	SHUCA_BERRY_ITEM("Shuca Berry"),
	COBA_BERRY_ITEM("Coba Berry"),
	PAYAPA_BERRY_ITEM("Payapa Berry"),
	TANGA_BERRY_ITEM("Tanga Berry"),
	CHARTI_BERRY_ITEM("Charti Berry"),
	KASIB_BERRY_ITEM("Kasib Berry"),
	HABAN_BERRY_ITEM("Haban Berry"),
	COLBUR_BERRY_ITEM("Colbur Berry"),
	BABIRI_BERRY_ITEM("Babiri Berry"),
	CHILAN_BERRY_ITEM("Chilan Berry"),
	LIECHI_BERRY_ITEM("Liechi Berry"),
	GANLON_BERRY_ITEM("Ganlon Berry"),
	SALAC_BERRY_ITEM("Salac Berry"),
	PETAYA_BERRY_ITEM("Petaya Berry"),
	APICOT_BERRY_ITEM("Apicot Berry"),
	LANSAT_BERRY_ITEM("Lansat Berry"),
	STARF_BERRY_ITEM("Starf Berry"),
	COMET_SHARD_ITEM("Comet Shard"),
	TINY_MUSHROOM_ITEM("Tiny Mushroom"),
	BIG_MUSHROOM_ITEM("Big Mushroom"),
	BALM_MUSHROOM_ITEM("Balm Mushroom"),
	NUGGET_ITEM("Nugget"),
	BIG_NUGGET_ITEM("Big Nugget"),
	PEARL_ITEM("Pearl"),
	BIG_PEARL_ITEM("Big Pearl"),
	STARDUST_ITEM("Stardust"),
	STAR_PIECE_ITEM("Star Piece"),
	RARE_BONE_ITEM("Rare Bone"),
	HONEY_ITEM("Honey"),
	EVIOLITE_ITEM("Eviolite"),
	HEART_SCALE_ITEM("Heart Scale"),
	REPEL_ITEM("Repel"),
	SUPER_REPEL_ITEM("Super Repel"),
	MAX_REPEL_ITEM("Max Repel");

	// EVERYTHING ABOVE IS GENERATED ###
	
	private String name;

	private Namesies(String name)
	{
		this.name = name;
	}

	public String getName()
	{
		return this.name;
	}
	
	public static Namesies getValueOf(String className, String superClass)
	{
		return Namesies.valueOf(Namesies.getNamesies(className, superClass));
	}
	
	public static String getNamesies(String className, String superClass)
	{
		className = className.replace(" ", "");
		
		char[] classChar = (className + superClass).toCharArray();
		String enumName = classChar[0] + "";
		
		for (int i = 1; i < classChar.length; i++)
		{
			if (isUpper(classChar[i]) && !isUpper(classChar[i - 1]))
			{
				enumName += "_";
			}
			
			enumName += classChar[i];
		}
		
		return enumName.toUpperCase();
	}
	
	private static boolean isUpper(char c)
	{
		return c >= 'A' && c <= 'Z';
	}
}

